import {
  createElement,
  createPropsSchema,
  dynamicProperties,
  props,
  traits,
  useAction,
  useDynamicProperty,
  useRenderMode,
  values,
} from '@hmiproject/helio-sdk';
import { Fragment } from 'react';
import { OpenBridgeTheme } from '../utils/OpenBridgeTheme';
import { namespace } from '../namespace';
import { FlatCompass, type FlatCompassProps } from '../components/FlatCompass';
import {
  optionalBoolean,
  optionalNumber,
  optionalString,
  parseEnumList,
  toFiniteNumber,
} from '../utils/valueMapping';

/**
 * OpenBridge flat compass (`<obc-compass-flat>`) as a HELIO Control.
 *
 * Generated by `create-element.mjs` from the OpenBridge custom elements manifest.
 */
export const flatCompassElement = createElement(namespace, {
  name: 'OpenBridge Flat Compass',
  description:
    'Horizontal strip compass with HDG/COG arrows and optional rate-of-turn indicator (OpenBridge design system).',
  category: 'OpenBridge',
  icon: { name: 'Compass' },

  traits: [traits.Control],

  propsGroups: {
    data: { label: 'Values' },
    display: { label: 'Display' },
    rot: { label: 'ROT', defaultClosed: true },
    interaction: { label: 'Interaction', defaultClosed: true },
  },

  propsSchema: createPropsSchema().initial({
    FOVIndicator: props.DynamicProperty({
      label: 'FOV indicator (default false)',
      propGroup: 'display',
      valueType: 'Boolean',
      optional: true,
    }),
    heading: props.DynamicProperty({
      label: 'Heading',
      propGroup: 'data',
      valueType: 'NumericValue',
      optional: false,
      defaultValue: dynamicProperties.StaticValue(0),
    }),
    courseOverGround: props.DynamicProperty({
      label: 'Course over ground (default 0)',
      propGroup: 'data',
      valueType: 'NumericValue',
      optional: true,
    }),
    tickInterval: props.DynamicProperty({
      label: 'Tick interval (default 5)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    FOV: props.DynamicProperty({
      label: 'FOV (default 45)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    minFOV: props.DynamicProperty({
      label: 'Min FOV (default 45)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    maxFOV: props.DynamicProperty({
      label: 'Max FOV (default 180)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    enhancedPriority: props.DynamicProperty({
      label: 'Enhanced priority (blue)',
      propGroup: 'display',
      valueType: 'Boolean',
      optional: true,
    }),
    priorityElements: props.DynamicProperty({
      label: 'Priority elements (hdg, cog, rot) (default hdg)',
      propGroup: 'display',
      valueType: 'String',
      optional: true,
    }),
    rotType: props.Enum({
      label: 'ROT type',
      propGroup: 'rot',
      options: ['dots', 'bar'],
      optional: true,
    }),
    rateOfTurnDegreesPerMinute: props.DynamicProperty({
      label: 'Rate of turn degrees per minute',
      propGroup: 'data',
      valueType: 'NumericValue',
      optional: true,
    }),
    rotDotAnimationFactor: props.DynamicProperty({
      label: 'ROT dot animation factor (default 18)',
      propGroup: 'rot',
      valueType: 'NumericValue',
      optional: true,
    }),
    rotMaxValue: props.DynamicProperty({
      label: 'ROT max value (default 60)',
      propGroup: 'rot',
      valueType: 'NumericValue',
      optional: true,
    }),
    rotArcExtent: props.DynamicProperty({
      label: 'ROT arc extent (default 60)',
      propGroup: 'rot',
      valueType: 'NumericValue',
      optional: true,
    }),
    rotPortStarboard: props.DynamicProperty({
      label: 'ROT port starboard (default false)',
      propGroup: 'rot',
      valueType: 'Boolean',
      optional: true,
    }),
    rotAtZeroDeadband: props.DynamicProperty({
      label: 'ROT at zero deadband',
      propGroup: 'rot',
      valueType: 'NumericValue',
      optional: true,
    }),
    hasReadout: props.DynamicProperty({
      label: 'Has readout (default false)',
      propGroup: 'display',
      valueType: 'Boolean',
      optional: true,
    }),
    label: props.DynamicProperty({
      label: 'Label (default HDG)',
      propGroup: 'display',
      valueType: 'String',
      optional: true,
    }),
    unit: props.DynamicProperty({
      label: 'Unit (default DEG)',
      propGroup: 'display',
      valueType: 'String',
      optional: true,
    }),
    fractionDigits: props.DynamicProperty({
      label: 'Fraction digits (default 0)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    onClick: props.Action({
      label: 'On click',
      propGroup: 'interaction',
      optional: true,
    }),
  }),

  Component(p) {
    const renderMode = useRenderMode();
    const interactive = renderMode !== 'PreviewEdit';

    const FOVIndicatorDp = useDynamicProperty(p.FOVIndicator, { valueType: values.Boolean() });
    const headingDp = useDynamicProperty(p.heading, { valueType: values.Number() });
    const courseOverGroundDp = useDynamicProperty(p.courseOverGround, {
      valueType: values.Number(),
    });
    const tickIntervalDp = useDynamicProperty(p.tickInterval, { valueType: values.Number() });
    const FOVDp = useDynamicProperty(p.FOV, { valueType: values.Number() });
    const minFOVDp = useDynamicProperty(p.minFOV, { valueType: values.Number() });
    const maxFOVDp = useDynamicProperty(p.maxFOV, { valueType: values.Number() });
    const enhancedPriorityDp = useDynamicProperty(p.enhancedPriority, {
      valueType: values.Boolean(),
    });
    const priorityElementsDp = useDynamicProperty(p.priorityElements, {
      valueType: values.String(),
    });
    const rateOfTurnDegreesPerMinuteDp = useDynamicProperty(p.rateOfTurnDegreesPerMinute, {
      valueType: values.Number(),
    });
    const rotDotAnimationFactorDp = useDynamicProperty(p.rotDotAnimationFactor, {
      valueType: values.Number(),
    });
    const rotMaxValueDp = useDynamicProperty(p.rotMaxValue, { valueType: values.Number() });
    const rotArcExtentDp = useDynamicProperty(p.rotArcExtent, { valueType: values.Number() });
    const rotPortStarboardDp = useDynamicProperty(p.rotPortStarboard, {
      valueType: values.Boolean(),
    });
    const rotAtZeroDeadbandDp = useDynamicProperty(p.rotAtZeroDeadband, {
      valueType: values.Number(),
    });
    const hasReadoutDp = useDynamicProperty(p.hasReadout, { valueType: values.Boolean() });
    const labelDp = useDynamicProperty(p.label, { valueType: values.String() });
    const unitDp = useDynamicProperty(p.unit, { valueType: values.String() });
    const fractionDigitsDp = useDynamicProperty(p.fractionDigits, { valueType: values.Number() });

    const onClick = useAction(p.onClick);

    // Dynamic properties need to be mounted to subscribe to value changes.
    const subscriptions = [
      FOVIndicatorDp,
      headingDp,
      courseOverGroundDp,
      tickIntervalDp,
      FOVDp,
      minFOVDp,
      maxFOVDp,
      enhancedPriorityDp,
      priorityElementsDp,
      rateOfTurnDegreesPerMinuteDp,
      rotDotAnimationFactorDp,
      rotMaxValueDp,
      rotArcExtentDp,
      rotPortStarboardDp,
      rotAtZeroDeadbandDp,
      hasReadoutDp,
      labelDp,
      unitDp,
      fractionDigitsDp,
    ];

    const headingRaw = headingDp.canRead === false ? undefined : toFiniteNumber(headingDp.value);

    const clickable = onClick.canCall === true && interactive;

    return (
      <OpenBridgeTheme>
        {subscriptions.map((dp, index) => (
          <Fragment key={index}>{dp.render()}</Fragment>
        ))}
        {onClick.render()}

        <FlatCompass
          FOVIndicator={optionalBoolean(p.FOVIndicator, FOVIndicatorDp) ?? false}
          heading={headingRaw ?? 0}
          courseOverGround={
            optionalNumber(p.courseOverGround, courseOverGroundDp) ?? headingRaw ?? 0
          }
          tickInterval={optionalNumber(p.tickInterval, tickIntervalDp) ?? 5}
          FOV={optionalNumber(p.FOV, FOVDp) ?? 45}
          minFOV={optionalNumber(p.minFOV, minFOVDp) ?? 45}
          maxFOV={optionalNumber(p.maxFOV, maxFOVDp) ?? 180}
          priority={
            (optionalBoolean(p.enhancedPriority, enhancedPriorityDp)
              ? 'enhanced'
              : 'regular') as FlatCompassProps['priority']
          }
          priorityElements={
            (p.priorityElements === undefined
              ? undefined
              : parseEnumList(priorityElementsDp.value, [
                  'hdg',
                  'cog',
                  'rot',
                ])) as FlatCompassProps['priorityElements']
          }
          rotType={p.rotType as FlatCompassProps['rotType']}
          rateOfTurnDegreesPerMinute={
            optionalNumber(p.rateOfTurnDegreesPerMinute, rateOfTurnDegreesPerMinuteDp) ?? 0
          }
          rotDotAnimationFactor={
            optionalNumber(p.rotDotAnimationFactor, rotDotAnimationFactorDp) ?? 18
          }
          rotMaxValue={optionalNumber(p.rotMaxValue, rotMaxValueDp) ?? 60}
          rotArcExtent={optionalNumber(p.rotArcExtent, rotArcExtentDp) ?? 60}
          rotPortStarboard={optionalBoolean(p.rotPortStarboard, rotPortStarboardDp) ?? false}
          rotAtZeroDeadband={optionalNumber(p.rotAtZeroDeadband, rotAtZeroDeadbandDp)}
          hasReadout={optionalBoolean(p.hasReadout, hasReadoutDp) ?? false}
          label={optionalString(p.label, labelDp) ?? 'HDG'}
          unit={optionalString(p.unit, unitDp) ?? 'DEG'}
          fractionDigits={optionalNumber(p.fractionDigits, fractionDigitsDp) ?? 0}
          onClick={clickable ? onClick.call : undefined}
        />
      </OpenBridgeTheme>
    );
  },
});
