import {
  createElement,
  createPropsSchema,
  dynamicProperties,
  props,
  traits,
  useAction,
  useDynamicProperty,
  useRenderMode,
  values,
} from '@hmiproject/helio-sdk';
import { AdviceType } from '@oicl/openbridge-webcomponents/dist/navigation-instruments/watch/advice.js';
import { Fragment } from 'react';
import { namespace } from '../namespace';
import { RadialGauge, type RadialGaugeProps } from '../components/RadialGauge';
import {
  buildLinearAdvices,
  deriveInstrumentState,
  optionalBoolean,
  optionalNumber,
  optionalString,
  toFiniteNumber,
} from '../utils/valueMapping';

/**
 * OpenBridge radial gauge (`<obc-gauge-radial>`) as a HELIO Control.
 *
 * Generated by `scripts/create-element.mjs` from the OpenBridge custom
 * elements manifest.
 */
export const radialGaugeElement = createElement(namespace, {
  name: 'OpenBridge Radial Gauge',
  description: 'Configurable radial gauge for generic numeric values (OpenBridge design system).',
  category: 'OpenBridge',
  icon: { name: 'Tachometer' },

  traits: [traits.Control],

  propsGroups: {
    data: { label: 'Values' },
    setpoint: { label: 'Setpoint' },
    display: { label: 'Display' },
    advicesZones: { label: 'Advice zones', defaultClosed: true },
    interaction: { label: 'Interaction', defaultClosed: true },
  },

  propsSchema: createPropsSchema().initial({
    isOff: props.DynamicProperty({
      label: 'Instrument off',
      propGroup: 'data',
      valueType: 'Boolean',
      optional: true,
    }),
    isLoading: props.DynamicProperty({
      label: 'Instrument loading',
      propGroup: 'data',
      valueType: 'Boolean',
      optional: true,
    }),
    value: props.DynamicProperty({
      label: 'Value',
      propGroup: 'data',
      valueType: 'NumericValue',
      optional: false,
      defaultValue: dynamicProperties.StaticValue(0),
    }),
    maxValue: props.DynamicProperty({
      label: 'Max value (default 100)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    minValue: props.DynamicProperty({
      label: 'Min value (default 0)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    showLabels: props.DynamicProperty({
      label: 'Show labels (default false)',
      propGroup: 'display',
      valueType: 'Boolean',
      optional: true,
    }),
    primaryTickmarkInterval: props.DynamicProperty({
      label: 'Primary tickmark interval (default 50)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    secondaryTickmarkInterval: props.DynamicProperty({
      label: 'Secondary tickmark interval (default 10)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    tertiaryTickmarkInterval: props.DynamicProperty({
      label: 'Tertiary tickmark interval',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    enhancedPriority: props.DynamicProperty({
      label: 'Enhanced priority (blue)',
      propGroup: 'display',
      valueType: 'Boolean',
      optional: true,
    }),
    type: props.Enum({
      label: 'Type',
      propGroup: 'display',
      options: ['filled', 'bar', 'needle'],
      optional: true,
    }),
    tickmarksInside: props.DynamicProperty({
      label: 'Tickmarks inside (default false)',
      propGroup: 'display',
      valueType: 'Boolean',
      optional: true,
    }),
    tickmarkStyle: props.Enum({
      label: 'Tickmark style',
      propGroup: 'display',
      options: ['regular', 'enhanced'],
      optional: true,
    }),
    adviceEnabled: props.DynamicProperty({
      label: 'Advice zone enabled',
      propGroup: 'advicesZones',
      valueType: 'Boolean',
      optional: true,
    }),
    adviceMin: props.DynamicProperty({
      label: 'Advice zone from',
      propGroup: 'advicesZones',
      valueType: 'NumericValue',
      optional: true,
    }),
    adviceMax: props.DynamicProperty({
      label: 'Advice zone to',
      propGroup: 'advicesZones',
      valueType: 'NumericValue',
      optional: true,
    }),
    adviceHinted: props.DynamicProperty({
      label: 'Advice zone hinted',
      propGroup: 'advicesZones',
      valueType: 'Boolean',
      optional: true,
    }),
    cautionEnabled: props.DynamicProperty({
      label: 'Caution zone enabled',
      propGroup: 'advicesZones',
      valueType: 'Boolean',
      optional: true,
    }),
    cautionMin: props.DynamicProperty({
      label: 'Caution zone from',
      propGroup: 'advicesZones',
      valueType: 'NumericValue',
      optional: true,
    }),
    cautionMax: props.DynamicProperty({
      label: 'Caution zone to',
      propGroup: 'advicesZones',
      valueType: 'NumericValue',
      optional: true,
    }),
    cautionHinted: props.DynamicProperty({
      label: 'Caution zone hinted',
      propGroup: 'advicesZones',
      valueType: 'Boolean',
      optional: true,
    }),
    sector: props.Enum({
      label: 'Sector',
      propGroup: 'display',
      options: ['270', '180', '90-left', '90-right'],
      optional: true,
    }),
    horizontalAlignment: props.Enum({
      label: 'Horizontal alignment',
      propGroup: 'display',
      options: ['left', 'center', 'right'],
      optional: true,
    }),
    verticalAlignment: props.Enum({
      label: 'Vertical alignment',
      propGroup: 'display',
      options: ['top', 'center', 'bottom'],
      optional: true,
    }),
    hasReadout: props.DynamicProperty({
      label: 'Has readout (default false)',
      propGroup: 'display',
      valueType: 'Boolean',
      optional: true,
    }),
    label: props.DynamicProperty({
      label: 'Label',
      propGroup: 'display',
      valueType: 'String',
      optional: true,
    }),
    unit: props.DynamicProperty({
      label: 'Unit',
      propGroup: 'display',
      valueType: 'String',
      optional: true,
    }),
    fractionDigits: props.DynamicProperty({
      label: 'Fraction digits (default 0)',
      propGroup: 'display',
      valueType: 'NumericValue',
      optional: true,
    }),
    setpoint: props.DynamicProperty({
      label: 'Setpoint',
      propGroup: 'setpoint',
      valueType: 'NumericValue',
      optional: true,
    }),
    atSetpoint: props.DynamicProperty({
      label: 'At setpoint (default false)',
      propGroup: 'setpoint',
      valueType: 'Boolean',
      optional: true,
    }),
    autoAtSetpoint: props.DynamicProperty({
      label: 'Auto at setpoint (default true)',
      propGroup: 'setpoint',
      valueType: 'Boolean',
      optional: true,
    }),
    autoAtSetpointDeadband: props.DynamicProperty({
      label: 'Auto at setpoint deadband',
      propGroup: 'setpoint',
      valueType: 'NumericValue',
      optional: true,
    }),
    setpointAtZeroDeadband: props.DynamicProperty({
      label: 'Setpoint at zero deadband',
      propGroup: 'setpoint',
      valueType: 'NumericValue',
      optional: true,
    }),
    setpointOverride: props.DynamicProperty({
      label: 'Setpoint override (default false)',
      propGroup: 'setpoint',
      valueType: 'Boolean',
      optional: true,
    }),
    animateSetpoint: props.DynamicProperty({
      label: 'Animate setpoint (default false)',
      propGroup: 'setpoint',
      valueType: 'Boolean',
      optional: true,
    }),
    onClick: props.Action({
      label: 'On click',
      propGroup: 'interaction',
      optional: true,
    }),
  }),

  Component(p) {
    const renderMode = useRenderMode();

    const isOffDp = useDynamicProperty(p.isOff, { valueType: values.Boolean() });
    const isLoadingDp = useDynamicProperty(p.isLoading, { valueType: values.Boolean() });
    const valueDp = useDynamicProperty(p.value, { valueType: values.Number() });
    const maxValueDp = useDynamicProperty(p.maxValue, { valueType: values.Number() });
    const minValueDp = useDynamicProperty(p.minValue, { valueType: values.Number() });
    const showLabelsDp = useDynamicProperty(p.showLabels, { valueType: values.Boolean() });
    const primaryTickmarkIntervalDp = useDynamicProperty(p.primaryTickmarkInterval, {
      valueType: values.Number(),
    });
    const secondaryTickmarkIntervalDp = useDynamicProperty(p.secondaryTickmarkInterval, {
      valueType: values.Number(),
    });
    const tertiaryTickmarkIntervalDp = useDynamicProperty(p.tertiaryTickmarkInterval, {
      valueType: values.Number(),
    });
    const enhancedPriorityDp = useDynamicProperty(p.enhancedPriority, {
      valueType: values.Boolean(),
    });
    const tickmarksInsideDp = useDynamicProperty(p.tickmarksInside, {
      valueType: values.Boolean(),
    });
    const adviceEnabledDp = useDynamicProperty(p.adviceEnabled, { valueType: values.Boolean() });
    const adviceMinDp = useDynamicProperty(p.adviceMin, { valueType: values.Number() });
    const adviceMaxDp = useDynamicProperty(p.adviceMax, { valueType: values.Number() });
    const adviceHintedDp = useDynamicProperty(p.adviceHinted, { valueType: values.Boolean() });
    const cautionEnabledDp = useDynamicProperty(p.cautionEnabled, { valueType: values.Boolean() });
    const cautionMinDp = useDynamicProperty(p.cautionMin, { valueType: values.Number() });
    const cautionMaxDp = useDynamicProperty(p.cautionMax, { valueType: values.Number() });
    const cautionHintedDp = useDynamicProperty(p.cautionHinted, { valueType: values.Boolean() });
    const hasReadoutDp = useDynamicProperty(p.hasReadout, { valueType: values.Boolean() });
    const labelDp = useDynamicProperty(p.label, { valueType: values.String() });
    const unitDp = useDynamicProperty(p.unit, { valueType: values.String() });
    const fractionDigitsDp = useDynamicProperty(p.fractionDigits, { valueType: values.Number() });
    const setpointDp = useDynamicProperty(p.setpoint, { valueType: values.Number() });
    const atSetpointDp = useDynamicProperty(p.atSetpoint, { valueType: values.Boolean() });
    const autoAtSetpointDp = useDynamicProperty(p.autoAtSetpoint, { valueType: values.Boolean() });
    const autoAtSetpointDeadbandDp = useDynamicProperty(p.autoAtSetpointDeadband, {
      valueType: values.Number(),
    });
    const setpointAtZeroDeadbandDp = useDynamicProperty(p.setpointAtZeroDeadband, {
      valueType: values.Number(),
    });
    const setpointOverrideDp = useDynamicProperty(p.setpointOverride, {
      valueType: values.Boolean(),
    });
    const animateSetpointDp = useDynamicProperty(p.animateSetpoint, {
      valueType: values.Boolean(),
    });

    const onClick = useAction(p.onClick);

    // Dynamic properties need to be mounted to subscribe to value changes.
    const subscriptions = [
      isOffDp,
      isLoadingDp,
      valueDp,
      maxValueDp,
      minValueDp,
      showLabelsDp,
      primaryTickmarkIntervalDp,
      secondaryTickmarkIntervalDp,
      tertiaryTickmarkIntervalDp,
      enhancedPriorityDp,
      tickmarksInsideDp,
      adviceEnabledDp,
      adviceMinDp,
      adviceMaxDp,
      adviceHintedDp,
      cautionEnabledDp,
      cautionMinDp,
      cautionMaxDp,
      cautionHintedDp,
      hasReadoutDp,
      labelDp,
      unitDp,
      fractionDigitsDp,
      setpointDp,
      atSetpointDp,
      autoAtSetpointDp,
      autoAtSetpointDeadbandDp,
      setpointAtZeroDeadbandDp,
      setpointOverrideDp,
      animateSetpointDp,
    ];

    const valueRaw = valueDp.canRead === false ? undefined : toFiniteNumber(valueDp.value);

    const clickable = onClick.canCall === true && renderMode !== 'PreviewEdit';

    return (
      <Fragment>
        {subscriptions.map((dp, index) => (
          <Fragment key={index}>{dp.render()}</Fragment>
        ))}
        {onClick.render()}

        <RadialGauge
          value={valueRaw ?? 0}
          maxValue={optionalNumber(p.maxValue, maxValueDp) ?? 100}
          minValue={optionalNumber(p.minValue, minValueDp) ?? 0}
          showLabels={optionalBoolean(p.showLabels, showLabelsDp) ?? false}
          primaryTickmarkInterval={
            optionalNumber(p.primaryTickmarkInterval, primaryTickmarkIntervalDp) ?? 50
          }
          secondaryTickmarkInterval={
            optionalNumber(p.secondaryTickmarkInterval, secondaryTickmarkIntervalDp) ?? 10
          }
          tertiaryTickmarkInterval={optionalNumber(
            p.tertiaryTickmarkInterval,
            tertiaryTickmarkIntervalDp,
          )}
          state={deriveInstrumentState({
            isOff: optionalBoolean(p.isOff, isOffDp),
            isLoading: optionalBoolean(p.isLoading, isLoadingDp),
            valueAvailable: valueRaw !== undefined,
          })}
          priority={
            (optionalBoolean(p.enhancedPriority, enhancedPriorityDp)
              ? 'enhanced'
              : 'regular') as RadialGaugeProps['priority']
          }
          type={p.type as RadialGaugeProps['type']}
          tickmarksInside={optionalBoolean(p.tickmarksInside, tickmarksInsideDp) ?? false}
          tickmarkStyle={p.tickmarkStyle as RadialGaugeProps['tickmarkStyle']}
          advices={
            buildLinearAdvices([
              {
                type: AdviceType.advice,
                enabled: optionalBoolean(p.adviceEnabled, adviceEnabledDp),
                min: optionalNumber(p.adviceMin, adviceMinDp),
                max: optionalNumber(p.adviceMax, adviceMaxDp),
                hinted: optionalBoolean(p.adviceHinted, adviceHintedDp),
              },
              {
                type: AdviceType.caution,
                enabled: optionalBoolean(p.cautionEnabled, cautionEnabledDp),
                min: optionalNumber(p.cautionMin, cautionMinDp),
                max: optionalNumber(p.cautionMax, cautionMaxDp),
                hinted: optionalBoolean(p.cautionHinted, cautionHintedDp),
              },
            ]).map(({ min, max, ...rest }) => ({
              ...rest,
              minValue: min,
              maxValue: max,
            })) as RadialGaugeProps['advices']
          }
          sector={p.sector as RadialGaugeProps['sector']}
          horizontalAlignment={p.horizontalAlignment as RadialGaugeProps['horizontalAlignment']}
          verticalAlignment={p.verticalAlignment as RadialGaugeProps['verticalAlignment']}
          hasReadout={optionalBoolean(p.hasReadout, hasReadoutDp) ?? false}
          label={optionalString(p.label, labelDp) ?? ''}
          unit={optionalString(p.unit, unitDp) ?? ''}
          fractionDigits={optionalNumber(p.fractionDigits, fractionDigitsDp) ?? 0}
          setpoint={optionalNumber(p.setpoint, setpointDp)}
          atSetpoint={optionalBoolean(p.atSetpoint, atSetpointDp) ?? false}
          autoAtSetpoint={optionalBoolean(p.autoAtSetpoint, autoAtSetpointDp) ?? true}
          autoAtSetpointDeadband={optionalNumber(
            p.autoAtSetpointDeadband,
            autoAtSetpointDeadbandDp,
          )}
          setpointAtZeroDeadband={optionalNumber(
            p.setpointAtZeroDeadband,
            setpointAtZeroDeadbandDp,
          )}
          setpointOverride={optionalBoolean(p.setpointOverride, setpointOverrideDp) ?? false}
          animateSetpoint={optionalBoolean(p.animateSetpoint, animateSetpointDp) ?? false}
          onClick={clickable ? onClick.call : undefined}
        />
      </Fragment>
    );
  },
});
