import type { ObcCompassFlat as ObcCompassFlatElement } from '@oicl/openbridge-webcomponents/dist/navigation-instruments/compass-flat/compass-flat.js';
import { ObcCompassFlat } from '@oicl/openbridge-webcomponents-react/navigation-instruments/compass-flat/compass-flat.js';
import { className, cx } from '@hmiproject/helio-sdk';
import { AutoSizer } from '../utils/AutoSizer';
import { definedProps } from '../utils/valueMapping';

export type FlatCompassProps = Partial<
  Pick<
    ObcCompassFlatElement,
    | 'FOVIndicator'
    | 'heading'
    | 'courseOverGround'
    | 'tickInterval'
    | 'FOV'
    | 'minFOV'
    | 'maxFOV'
    | 'priority'
    | 'priorityElements'
    | 'rotType'
    | 'rateOfTurnDegreesPerMinute'
    | 'rotDotAnimationFactor'
    | 'rotMaxValue'
    | 'rotArcExtent'
    | 'rotPortStarboard'
    | 'rotAtZeroDeadband'
    | 'hasReadout'
    | 'label'
    | 'unit'
    | 'fractionDigits'
  >
> & {
  onClick?: () => void;
};

const classNames = {
  root: className({
    minHeight: 48,
    fontFamily: "'Noto Sans', sans-serif",
  }),
  clickable: className({ cursor: 'pointer' }),
};

/**
 * Presentational wrapper around OpenBridge's `<obc-compass-flat>`. Receives fully
 * resolved values; all HELIO dynamic property handling happens in the element.
 * The instrument fills the available space.
 *
 * Generated by `scripts/create-element.mjs`.
 */
export function FlatCompass({ onClick, ...props }: FlatCompassProps) {
  return (
    <AutoSizer className={cx(classNames.root, onClick && classNames.clickable)}>
      {({ width, height }) => {
        return (
          <ObcCompassFlat
            style={{ display: 'block', width, height }}
            onClick={onClick}
            {...definedProps(props)}
          />
        );
      }}
    </AutoSizer>
  );
}
