import type { ObcGaugeRadial as ObcGaugeRadialElement } from '@oicl/openbridge-webcomponents/dist/navigation-instruments/gauge-radial/gauge-radial.js';
import { ObcGaugeRadial } from '@oicl/openbridge-webcomponents-react/navigation-instruments/gauge-radial/gauge-radial.js';
import { className, cx } from '@hmiproject/helio-sdk';
import { AutoSizer } from '../utils/AutoSizer';
import { definedProps } from '../utils/valueMapping';

export type RadialGaugeProps = Partial<
  Pick<
    ObcGaugeRadialElement,
    | 'value'
    | 'maxValue'
    | 'minValue'
    | 'showLabels'
    | 'primaryTickmarkInterval'
    | 'secondaryTickmarkInterval'
    | 'tertiaryTickmarkInterval'
    | 'state'
    | 'priority'
    | 'type'
    | 'tickmarksInside'
    | 'tickmarkStyle'
    | 'advices'
    | 'sector'
    | 'horizontalAlignment'
    | 'verticalAlignment'
    | 'hasReadout'
    | 'label'
    | 'unit'
    | 'fractionDigits'
    | 'setpoint'
    | 'atSetpoint'
    | 'autoAtSetpoint'
    | 'autoAtSetpointDeadband'
    | 'setpointAtZeroDeadband'
    | 'setpointOverride'
    | 'animateSetpoint'
  >
> & { onClick?: () => void };

const classNames = {
  root: className({
    minHeight: 120,
    fontFamily: "'Noto Sans', sans-serif",
  }),
  clickable: className({ cursor: 'pointer' }),
};

/**
 * Presentational wrapper around OpenBridge's `<obc-gauge-radial>`. Receives fully
 * resolved values; all HELIO dynamic property handling happens in the element.
 * The component is kept square and scaled to the largest size that fits.
 *
 * Generated by `create-element.mjs`.
 */
export function RadialGauge({ onClick, ...props }: RadialGaugeProps) {
  return (
    <AutoSizer className={cx(classNames.root, onClick && classNames.clickable)}>
      {({ width, height }) => {
        const size = Math.min(width, height);
        return (
          <ObcGaugeRadial
            style={{ display: 'block', width: size, height: size }}
            onClick={onClick}
            {...definedProps(props)}
          />
        );
      }}
    </AutoSizer>
  );
}
