/**
 * Generates a HELIO element for an OpenBridge web component (instruments,
 * indicators and automation symbols):
 *
 *   <src>/components/<Name>.tsx           presentational component
 *   <src>/components/<Name>.stories.tsx   Storybook stories (if Storybook is installed)
 *   <src>/elements/<Name>Element.tsx      HELIO element (props schema + DP resolution)
 *   docs/openbridge-<tag>.md              property reference
 *   <src>/main.tsx                        registration
 *
 * Properties, types, defaults and events come from the OpenBridge
 * `custom-elements.json` manifest and the `.d.ts` files of
 * `@oicl/openbridge-webcomponents` / `-react`.
 *
 * The script is self-contained and can be copied into any HELIO extension repo
 * that has `@hmiproject/helio-sdk`, `@oicl/openbridge-webcomponents` and
 * `@oicl/openbridge-webcomponents-react` installed. Missing runtime helpers
 * (`utils/AutoSizer.tsx`, `utils/valueMapping.ts`, …) are created from copies
 * embedded at the end of this file.
 *
 * Usage:
 *   node scripts/create-element.mjs <component> [options]
 *   node scripts/create-element.mjs --list [instruments|indicators|automation]
 *
 *   <component>            OpenBridge tag without `obc-`, e.g. `gauge-radial`, `pump`
 *   --name "Radial Gauge"  display name (default: derived from the tag)
 *   --primary a,b          main values: required DPs that drive the `loading` state
 *                          (default: first of value/heading/angle/… that exists)
 *   --shape square|fill|intrinsic
 *                          square = largest square that fits (radial instruments),
 *                          fill = use the whole container,
 *                          intrinsic = natural size, centered (automation symbols)
 *   --icon Pump            HELIO icon name
 *   --root <dir>           project root (default: nearest package.json from cwd)
 *   --src <dir>            source folder relative to the root (default: src)
 *   --main <file>          extension entry relative to the root (default: <src>/main.tsx)
 *   --no-stories / --no-docs / --no-register
 *   --force                overwrite previously generated files (never hand-written ones)
 *   --dry-run              print what would be generated, write nothing
 *   --print-runtime <file> print an embedded runtime helper, e.g. utils/valueMapping.ts
 *   --sync-runtime         update the embedded runtime helpers from <src> (maintainers)
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const GENERATED_MARKER = 'Generated by `create-element.mjs`';
/** Markers of files written by earlier versions of this script. */
const LEGACY_MARKERS = [
  'Generated by `scripts/create-element.mjs`',
  // Stories of the first version had no marker, only this comment.
  '// the instrument auto-sizes to its container.',
];
/** Runtime helpers embedded at the end of this file (copies of this repo's files). */
const SYNCED_RUNTIME_FILES = [
  'utils/AutoSizer.tsx',
  'utils/valueMapping.ts',
  'dynamicProperties/angleMath.ts',
];

// ── CLI ──────────────────────────────────────────────────────────────────

const FLAGS = ['force', 'dry-run', 'list', 'no-stories', 'no-docs', 'no-register', 'sync-runtime'];

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (!arg.startsWith('--')) args._.push(arg);
    else if (FLAGS.includes(arg.slice(2))) args[arg.slice(2)] = true;
    else args[arg.slice(2)] = argv[++i];
  }
  return args;
}

const args = parseArgs(process.argv.slice(2));

function fail(message) {
  console.error(`\x1b[31m${message}\x1b[0m`);
  process.exit(1);
}

const warnings = [];
const warn = (message) => warnings.push(message);

if (args['print-runtime']) {
  const source = runtimeFiles()[args['print-runtime']];
  if (!source) fail(`Unknown runtime file. Available: ${Object.keys(runtimeFiles()).join(', ')}`);
  process.stdout.write(source);
  process.exit(0);
}

// ── Project layout ───────────────────────────────────────────────────────

function findRoot() {
  if (args.root) return resolve(args.root);
  for (let dir = process.cwd(); ; dir = dirname(dir)) {
    if (existsSync(resolve(dir, 'package.json'))) return dir;
    if (dirname(dir) === dir) return resolve(dirname(SCRIPT_PATH), '..');
  }
}

const root = findRoot();
const srcDir = args.src ?? 'src';
const mainFile = args.main ?? `${srcDir}/main.tsx`;
const inRoot = (...parts) => resolve(root, ...parts);
const inSrc = (...parts) => resolve(root, srcDir, ...parts);

if (args['sync-runtime']) {
  const self = readFileSync(SCRIPT_PATH, 'utf8');
  // lastIndexOf: the marker strings also appear in this code.
  const start = self.lastIndexOf('// @runtime-files-start');
  const end = self.lastIndexOf('// @runtime-files-end');
  const entries = SYNCED_RUNTIME_FILES.map((file) => {
    const path = inSrc(file);
    if (!existsSync(path)) fail(`Cannot sync: ${relative(root, path)} is missing.`);
    return `  ${JSON.stringify(file)}: ${JSON.stringify(readFileSync(path, 'utf8'))},`;
  });
  const block = `// @runtime-files-start\n// prettier-ignore\nfunction syncedRuntimeFiles() {\n  return {\n${entries.map((e) => `  ${e}`).join('\n')}\n  };\n}\n`;
  writeFileSync(SCRIPT_PATH, self.slice(0, start) + block + self.slice(end));
  console.log(`Embedded runtime helpers updated from ${srcDir}/.`);
  process.exit(0);
}

function requirePackage(name) {
  const dir = inRoot('node_modules', name);
  if (!existsSync(dir)) fail(`Package ${name} is not installed. Run: npm install ${name}`);
  return dir;
}

const pkgDir = requirePackage('@oicl/openbridge-webcomponents');
const reactPkgDir = requirePackage('@oicl/openbridge-webcomponents-react');
requirePackage('@hmiproject/helio-sdk');
const manifest = JSON.parse(readFileSync(resolve(pkgDir, 'custom-elements.json'), 'utf8'));

// ── Component catalog ────────────────────────────────────────────────────

const CATEGORIES = {
  instruments: {
    label: 'Instruments',
    helioCategory: 'OpenBridge',
    storyPrefix: 'OpenBridge',
    docsPath: (tag) => `instruments-${tag}`,
  },
  indicators: {
    label: 'Indicators',
    helioCategory: 'OpenBridge Indicators',
    storyPrefix: 'OpenBridge/Indicators',
    docsPath: (tag, area) => (area === 'automation' ? undefined : `indicators-${tag}`),
  },
  automation: {
    label: 'Automation',
    helioCategory: 'OpenBridge Automation',
    storyPrefix: 'OpenBridge/Automation',
    docsPath: () => undefined,
  },
};

/** Same grouping as the OpenBridge Storybook. */
function categoryOf(mod, tag) {
  const area = mod.path.split('/')[1];
  if (area === 'navigation-instruments')
    return /-indicator$/.test(tag) ? 'indicators' : 'instruments';
  if (area === 'automation') return /^obc-indicator-/.test(tag) ? 'indicators' : 'automation';
  return undefined;
}

const catalog = manifest.modules.flatMap((mod) =>
  (mod.declarations ?? [])
    .filter((d) => d.customElement && d.tagName && categoryOf(mod, d.tagName))
    .map((declaration) => ({ mod, declaration, category: categoryOf(mod, declaration.tagName) })),
);

if (args.list) {
  const wanted = args._[0];
  if (wanted && !CATEGORIES[wanted]) {
    fail(`Unknown category "${wanted}". Use: ${Object.keys(CATEGORIES).join(', ')}`);
  }
  const tagsOf = (category) =>
    catalog
      .filter((entry) => entry.category === category)
      .map(({ declaration }) => declaration.tagName.replace(/^obc-/, ''))
      .sort();
  if (wanted) console.log(tagsOf(wanted).join('\n'));
  else {
    for (const [key, { label }] of Object.entries(CATEGORIES)) {
      const tags = tagsOf(key);
      console.log(`\n${label} (${tags.length})  – --list ${key}\n  ${tags.join('\n  ')}`);
    }
  }
  process.exit(0);
}

const tagArg = args._[0];
if (!tagArg) fail('Usage: node scripts/create-element.mjs <component> [options]  (see --list)');

const tag = tagArg.startsWith('obc-') ? tagArg : `obc-${tagArg}`;
const found = catalog.find(({ declaration }) => declaration.tagName === tag);
if (!found) fail(`No OpenBridge component <${tag}> found. Run with --list to see all.`);

const { mod, declaration, category } = found;
const categoryInfo = CATEGORIES[category];
const area = mod.path.split('/')[1];
const shortTag = tag.replace(/^obc-/, '');
const modulePath = mod.path.replace(/^src\//, '').replace(/\.ts$/, '');
const distDts = resolve(pkgDir, 'dist', `${modulePath}.d.ts`);
const reactDts = resolve(reactPkgDir, `${modulePath}.d.ts`);
const obcClass = declaration.name;
if (!existsSync(reactDts))
  fail(`React wrapper not found for <${tag}>: ${relative(root, reactDts)}`);

const toPascal = (s) =>
  s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
const toCamel = (s) => {
  const pascal = toPascal(s);
  return pascal[0].toLowerCase() + pascal.slice(1);
};
const toTitle = (s) =>
  s
    .split('-')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(' ');

const displayName = args.name ?? toTitle(shortTag);
const Name = toPascal(displayName);
const elementVar = `${toCamel(displayName)}Element`;
const propsType = `${Name}Props`;

// ── Type resolution from .d.ts files ─────────────────────────────────────

const dtsCache = new Map();
function readDts(file) {
  if (!dtsCache.has(file)) dtsCache.set(file, existsSync(file) ? readFileSync(file, 'utf8') : '');
  return dtsCache.get(file);
}

function importTarget(fromFile, spec) {
  if (spec.startsWith('.')) return resolve(dirname(fromFile), spec.replace(/\.js$/, '.d.ts'));
  return resolve(root, 'node_modules', spec.replace(/\.js$/, '.d.ts'));
}

const stripComments = (text) => text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');

function parseEnumBody(body) {
  const values = [];
  for (const line of stripComments(body).split(',')) {
    const match = line.trim().match(/^(\w+)\s*=\s*(.+)$/);
    if (!match) continue;
    const raw = match[2].trim();
    if (/^["'].*["']$/.test(raw)) values.push({ key: match[1], value: raw.slice(1, -1) });
    else if (/^-?\d+(\.\d+)?$/.test(raw)) values.push({ key: match[1], value: Number(raw) });
    else return undefined;
  }
  return values;
}

/** Parses `{ a: number; b?: string }` / `{a: number, b?: string}` into fields. */
function parseObjectBody(body) {
  return [...stripComments(body).matchAll(/(\w+)(\?)?\s*:\s*([^;,\n]+)[;,\n]?/g)].map((m) => ({
    name: m[1],
    optional: Boolean(m[2]),
    type: m[3].trim(),
  }));
}

/**
 * Resolves a type name to `{ kind: 'enum', values }` or
 * `{ kind: 'interface', fields }`, following imports and re-exports.
 */
function resolveTypeIn(name, file, depth = 0) {
  if (depth > 5 || !/^\w+$/.test(name)) return undefined;
  const text = readDts(file);

  const enumMatch = text.match(new RegExp(`export declare enum ${name}\\s*\\{([^}]*)\\}`));
  if (enumMatch) {
    const values = parseEnumBody(enumMatch[1]);
    return values?.length ? { kind: 'enum', values } : undefined;
  }

  const aliasMatch = text.match(new RegExp(`export type ${name}\\s*=\\s*([^;]+);`));
  if (aliasMatch) {
    const parts = aliasMatch[1].split('|').map((p) => p.trim());
    if (parts.every((p) => /^["'].*["']$/.test(p))) {
      return {
        kind: 'enum',
        values: parts.map((p) => ({ key: p.slice(1, -1), value: p.slice(1, -1) })),
      };
    }
    const objectMatch = aliasMatch[1].trim().match(/^\{([\s\S]*)\}$/);
    if (objectMatch) return { kind: 'interface', fields: parseObjectBody(objectMatch[1]) };
    return { kind: 'alias', text: aliasMatch[1].trim() };
  }

  const interfaceMatch = text.match(
    new RegExp(`export interface ${name}(?:\\s+extends[^{]+)?\\s*\\{([^}]*)\\}`),
  );
  if (interfaceMatch) return { kind: 'interface', fields: parseObjectBody(interfaceMatch[1]) };

  const refs = [
    ...text.matchAll(/(?:import|export)\s+(?:type\s+)?\{([^}]*)\}\s+from\s+'([^']+)'/g),
  ];
  for (const [, names, spec] of refs) {
    const hit = names
      .split(',')
      .map((n) => n.trim().replace(/^type\s+/, ''))
      .find((n) => n === name || n.endsWith(` as ${name}`));
    if (hit) {
      const original = hit.includes(' as ') ? hit.split(' as ')[0].trim() : hit;
      return resolveTypeIn(original, importTarget(file, spec), depth + 1);
    }
  }
  for (const [, spec] of text.matchAll(/export\s+\*\s+from\s+'([^']+)'/g)) {
    const result = resolveTypeIn(name, importTarget(file, spec), depth + 1);
    if (result) return result;
  }
  return undefined;
}

/** Name → declaring `.d.ts`, for types that are not reachable via imports. */
let declarationIndex;
function findDeclaration(name) {
  if (!declarationIndex) {
    declarationIndex = new Map();
    const dist = resolve(pkgDir, 'dist');
    for (const file of readdirSync(dist, { recursive: true })) {
      if (!String(file).endsWith('.d.ts')) continue;
      const path = resolve(dist, String(file));
      for (const [, found] of readDts(path).matchAll(
        /export (?:declare enum|type|interface) (\w+)/g,
      )) {
        if (!declarationIndex.has(found)) declarationIndex.set(found, path);
      }
    }
  }
  return declarationIndex.get(name);
}

/** Resolves a type starting from `file`, falling back to a package-wide lookup. */
function resolveType(name, file = distDts) {
  const direct = resolveTypeIn(name, file);
  if (direct) return direct;
  const declaredIn = /^\w+$/.test(name) ? findDeclaration(name) : undefined;
  return declaredIn && declaredIn !== file ? resolveTypeIn(name, declaredIn) : undefined;
}

/** The `.d.ts` a member is declared in (inherited members live in the base class file). */
function memberFile(field) {
  const module = field.inheritedFrom?.module;
  return module
    ? resolve(pkgDir, 'dist', module.replace(/^src\//, '').replace(/\.ts$/, '.d.ts'))
    : distDts;
}

// ── Member classification ────────────────────────────────────────────────

/**
 * IDE defaults that differ from the component default because HELIO places
 * elements in a layout box rather than on a diagram.
 */
const DEFAULT_OVERRIDES = {
  // `point` wraps automation symbols in a 0×0 px anchor, so they overflow the
  // HELIO box; `button` sizes the host to the full button incl. readouts.
  positioning: 'button',
};

const SKIPPED_NAMES = new Set(['faceDiameter', 'touching', 'loading', 'newSetpoint', 'ariaLabel']);
const PRIMARY_CANDIDATES = [
  'value',
  'heading',
  'angle',
  'speed',
  'depth',
  'pitch',
  'roll',
  'heave',
];
const DATA_NAMES =
  /^(value|heading|courseOverGround|rateOfTurn\w*|angle|thrust|speed\w*|depth|pitch|roll|heave|yaw|surge|sway|wind\w*|current\w*|bearing|rudder\w*|level|on|open|turnedOn|selectedPosition)$/;
/** Types that cannot come from a HELIO value (DOM nodes, templates, callbacks). */
const NOT_SERIALIZABLE = /(HTML\w*Element|\bElement\b|\bNode\b|TemplateResult|=>|\bFunction\b)/;
const PRIMITIVES = new Set(['number', 'string', 'boolean']);

const stripNullish = (type) =>
  type
    .split('|')
    .map((p) => p.trim())
    .filter((p) => p !== 'undefined' && p !== 'null')
    .join(' | ');

function parseDefault(raw, resolved) {
  if (raw === undefined) return undefined;
  const text = raw.trim();
  if (/^-?\d+(\.\d+)?$/.test(text)) return Number(text);
  if (text === 'true' || text === 'false') return text === 'true';
  if (/^'.*'$|^".*"$/.test(text)) return text.slice(1, -1);
  if (resolved?.kind === 'enum') {
    const lookup = (ref) => {
      const key = ref.trim().split('.').pop();
      const entry = resolved.values.find((v) => v.key === key);
      // Numeric enums are selected by key in the IDE.
      return entry && (resolved.numeric ? entry.key : entry.value);
    };
    if (/^\[.*\]$/s.test(text)) {
      return text
        .slice(1, -1)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
        .map(lookup)
        .filter((v) => v !== undefined);
    }
    return lookup(text);
  }
  return undefined;
}

/** Classifies a (nullish-stripped) type into a member kind. */
function classify(base, file = distDts) {
  if (PRIMITIVES.has(base)) return { kind: base };
  if (NOT_SERIALIZABLE.test(base)) return { skip: 'not serializable' };

  const unionParts = base.split('|').map((p) => p.trim());
  if (unionParts.length > 1) {
    if (unionParts.every((p) => /^["'].*["']$/.test(p))) {
      const values = unionParts.map((p) => ({ key: p.slice(1, -1), value: p.slice(1, -1) }));
      return { kind: 'enum', resolved: { kind: 'enum', values } };
    }
    if (unionParts.every((p) => PRIMITIVES.has(p) || /^["'].*["']$/.test(p))) {
      return { kind: 'primitive' };
    }
    return { kind: 'json' };
  }

  const arrayMatch = base.match(/^\((.+)\)\[\]$|^(\w+)\[\]$|^Array<(.+)>$/);
  if (arrayMatch) {
    const item = stripNullish(arrayMatch[1] ?? arrayMatch[2] ?? arrayMatch[3]);
    if (PRIMITIVES.has(item)) return { kind: 'list', itemType: item };
    if (item.split('|').every((p) => PRIMITIVES.has(p.trim()))) {
      return { kind: 'list', itemType: 'primitive' };
    }
    if (NOT_SERIALIZABLE.test(item)) return { skip: 'not serializable' };
    const resolved = resolveType(item, file);
    if (resolved?.kind === 'enum' && !resolved.values.some((v) => typeof v.value === 'number')) {
      return { kind: 'enumList', resolved };
    }
    if (resolved?.kind === 'interface') {
      const names = resolved.fields.map((f) => f.name);
      const minKey = names.find((n) => /^min/.test(n));
      const maxKey = names.find((n) => /^max/.test(n));
      if (names.includes('type') && names.includes('hinted') && minKey && maxKey) {
        return { kind: 'advice', minKey, maxKey, angle: minKey === 'minAngle' };
      }
    }
    return { kind: 'json' };
  }

  if (/^\w+$/.test(base)) {
    const resolved = resolveType(base, file);
    if (resolved?.kind === 'enum') {
      resolved.numeric = resolved.values.some((v) => typeof v.value === 'number');
      return { kind: 'enum', resolved };
    }
    if (resolved?.kind === 'alias') return classify(stripNullish(resolved.text), file);
    return { kind: 'json' };
  }
  return { kind: 'json' };
}

const skipped = [];
const members = [];

for (const field of declaration.members ?? []) {
  if (field.kind !== 'field' || field.static || field.readonly) continue;
  if (field.privacy && field.privacy !== 'public') continue;
  if (field.name.startsWith('_')) continue;
  const typeText = field.type?.text;
  const description = (field.description ?? '').replace(/\s+/g, ' ').trim();

  if (!typeText) continue; // methods / getters without type
  if (SKIPPED_NAMES.has(field.name) || /^new[A-Z]\w*Setpoint$/.test(field.name)) continue;
  if (/^departing/.test(field.name)) continue;
  if (field.deprecated || /^\*\*deprecated/i.test(description)) continue;

  const base = stripNullish(typeText);
  const member = { name: field.name, base, description };

  if (field.name === 'state' && base === 'InstrumentState')
    Object.assign(member, { kind: 'state' });
  else if (field.name === 'priority' && base === 'Priority')
    Object.assign(member, { kind: 'priority' });
  else {
    const result = classify(base, memberFile(field));
    if (result.skip) {
      skipped.push({ name: field.name, type: typeText, reason: result.skip });
      continue;
    }
    Object.assign(member, result);
  }
  if (member.kind === 'enum' || member.kind === 'enumList') {
    member.options = member.resolved.values.map((v) => (member.resolved.numeric ? v.key : v.value));
  }

  member.default = parseDefault(field.default, member.resolved);
  const defaultOverride = DEFAULT_OVERRIDES[member.name];
  if (defaultOverride !== undefined && member.options?.includes(defaultOverride)) {
    member.default = defaultOverride;
    member.defaultOverridden = true;
  }
  members.push(member);
}

// ── Events (from the React wrapper) ──────────────────────────────────────

/** Primitive payload fields of an event detail type (one nested level). */
function payloadFields(detailType) {
  const type = detailType ? stripNullish(detailType) : '';
  if (!type || type === 'void' || type === 'unknown' || type === 'any') return [];
  if (PRIMITIVES.has(type)) return [{ path: [], type }];
  const inline = type.match(/^\{([\s\S]*)\}$/);
  const resolved = inline
    ? { kind: 'interface', fields: parseObjectBody(inline[1]) }
    : (resolveType(type) ?? resolveType(type, reactDts));
  if (resolved?.kind !== 'interface') return [];
  return resolved.fields.flatMap((f) => {
    const fieldType = stripNullish(f.type);
    if (PRIMITIVES.has(fieldType)) return [{ path: [f.name], type: fieldType }];
    const nested = /^\w+$/.test(fieldType) ? resolveType(fieldType) : undefined;
    if (nested?.kind !== 'interface') return [];
    return nested.fields
      .filter((n) => PRIMITIVES.has(stripNullish(n.type)))
      .map((n) => ({ path: [f.name, n.name], type: stripNullish(n.type) }));
  });
}

const wrapperEvents = (() => {
  const text = readDts(reactDts);
  const block = text.match(/ReactWebComponent<\w+,\s*\{([\s\S]*?)\}>/);
  if (!block) return [];
  return [...block[1].matchAll(/(on\w+):\s*EventName<([^;]+)>;/g)].map(([, prop, eventType]) => {
    const detail = eventType.match(/^CustomEvent<([\s\S]+)>$/)?.[1];
    return { prop, detail };
  });
})();

const events = wrapperEvents
  .filter((e) => e.prop !== 'onClick')
  .map((e) => {
    const base = e.prop.replace(/^on/, '');
    const words = base.replace(/([a-z0-9])([A-Z])/g, '$1 $2').toLowerCase();
    return {
      prop: e.prop,
      label: `On ${words}`,
      words,
      actionVar: `${e.prop}Action`,
      targets: payloadFields(e.detail).map((f) => ({
        ...f,
        key: `${base[0].toLowerCase()}${base.slice(1)}${f.path.map(toPascal).join('') || 'Value'}Target`,
      })),
    };
  });

// ── Defaults per component ───────────────────────────────────────────────

const has = (kind) => members.some((m) => m.kind === kind);
const numberNames = members.filter((m) => m.kind === 'number').map((m) => m.name);

const primaryNames = args.primary
  ? args.primary.split(',').map((s) => s.trim())
  : // Automation symbols have no loading state, so a main value only helps instruments.
    category === 'instruments' || has('state')
    ? [PRIMARY_CANDIDATES.find((c) => numberNames.includes(c))].filter(Boolean)
    : [];
for (const name of primaryNames) {
  if (!numberNames.includes(name)) fail(`--primary ${name}: no numeric property with that name.`);
}

const supportsFaceDiameter = declaration.members?.some((m) => m.name === 'faceDiameter');
const shape =
  args.shape ??
  (supportsFaceDiameter ? 'square' : category === 'instruments' ? 'fill' : 'intrinsic');
if (!['square', 'fill', 'intrinsic'].includes(shape)) {
  fail('--shape must be "square", "fill" or "intrinsic"');
}

const ICON_RULES = [
  [/battery/, 'Battery'],
  [/pump/, 'Pump'],
  [/valve|damper/, 'Valve'],
  [/fan|thruster|propulsion|propeller|motor/, 'Fan'],
  [/filter/, 'Filter'],
  [/heat/, 'Heat'],
  [/resistor/, 'Resistor'],
  [/line|bus|router|separator/, 'Pipeline'],
  [
    /generator|transformer|converter|source|ground|capacitor|transistor|mosfet|diode|engine/,
    'Power',
  ],
  [/button|switch|logic|transmitter|badge|input/, 'Toggles'],
  [/tank/, 'CircleLiquidHalf'],
  [/compass|heading|bearing/, 'Compass'],
  [/speed/, 'Speed'],
  [/gauge|rot|rudder|pitch|roll|heave|depth|readout/, 'Tachometer'],
];
const icon = args.icon ?? ICON_RULES.find(([re]) => re.test(shortTag))?.[1] ?? 'Dashboard';

// ── Prop model ───────────────────────────────────────────────────────────

const ACRONYMS = new Set(['rot', 'hdg', 'cog', 'sog', 'stw', 'fov', 'json', 'id']);

const humanize = (name) =>
  name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .split(' ')
    .map((w, i) =>
      ACRONYMS.has(w.toLowerCase())
        ? w.toUpperCase()
        : i === 0
          ? w[0].toUpperCase() + w.slice(1)
          : /^[A-Z]{2,}/.test(w)
            ? w
            : w.toLowerCase(),
    )
    .join(' ');

const formatDefault = (value) => (Array.isArray(value) ? value.join(', ') : String(value));

/** Generic verbs that do not make a meaningful props group. */
const NON_GROUP_PREFIXES = new Set([
  'is',
  'has',
  'show',
  'hide',
  'min',
  'max',
  'auto',
  'at',
  'use',
  'enable',
]);
const RESERVED_GROUPS = new Set(['data', 'setpoint', 'display', 'events', 'interaction']);
const prefixOf = (name) => name.match(/^[a-z]+/)?.[0];

const prefixCounts = new Map();
for (const m of members) {
  const prefix = prefixOf(m.name);
  if (prefix) prefixCounts.set(prefix, (prefixCounts.get(prefix) ?? 0) + 1);
}

function groupFor(member) {
  if (primaryNames.includes(member.name) || DATA_NAMES.test(member.name)) return 'data';
  if (/setpoint/i.test(member.name)) return 'setpoint';
  const prefix = prefixOf(member.name);
  if (
    prefix &&
    prefixCounts.get(prefix) >= 3 &&
    prefixCounts.get(prefix) < members.length &&
    !NON_GROUP_PREFIXES.has(prefix) &&
    !RESERVED_GROUPS.has(prefix)
  ) {
    return prefix;
  }
  return 'display';
}

const reservedKeys = new Set([
  'isOff',
  'isLoading',
  'enhancedPriority',
  'onClick',
  ...events.flatMap((e) => [e.prop, ...e.targets.map((t) => t.key)]),
]);
for (const m of members) {
  if (reservedKeys.has(m.name)) fail(`Property name "${m.name}" collides with a generated prop.`);
}

/** Every HELIO prop that ends up in the schema, in order. */
const schemaProps = [];
const groups = new Map([['data', { label: 'Values' }]]);
const prefixGroups = new Map();

if (has('state')) {
  schemaProps.push(
    { key: 'isOff', group: 'data', kind: 'dpBoolean', label: 'Instrument off', optional: true },
    {
      key: 'isLoading',
      group: 'data',
      kind: 'dpBoolean',
      label: 'Instrument loading',
      optional: true,
    },
  );
}

const DP_KIND = {
  number: 'dpNumber',
  boolean: 'dpBoolean',
  string: 'dpString',
  primitive: 'dpPrimitive',
  list: 'dpAny',
  json: 'dpAny',
  enumList: 'dpString',
};

for (const m of members) {
  const group = groupFor(m);
  if (!RESERVED_GROUPS.has(group) && !prefixGroups.has(group)) {
    prefixGroups.set(group, { label: humanize(group), defaultClosed: true });
  }
  if (m.kind === 'state') continue;
  if (m.kind === 'priority') {
    schemaProps.push({
      key: 'enhancedPriority',
      group: 'display',
      kind: 'dpBoolean',
      label: 'Enhanced priority (blue)',
      optional: true,
      member: m,
    });
    continue;
  }
  const hint =
    m.default !== undefined && m.default !== '' && !(Array.isArray(m.default) && !m.default.length)
      ? ` (default ${formatDefault(m.default)})`
      : '';
  const label = humanize(m.name);

  if (m.kind === 'advice') {
    const prefix = m.name.replace(/Advices?$/, '').replace(/^advices?$/, '');
    const groupKey = `${m.name}Zones`;
    const unit = m.angle ? ' [°]' : '';
    groups.set(groupKey, {
      label: prefix ? `${humanize(prefix)} advice zones` : 'Advice zones',
      defaultClosed: true,
    });
    m.zoneKeys = {};
    for (const type of ['advice', 'caution']) {
      const k = (suffix) => (prefix ? `${prefix}${toPascal(type)}${suffix}` : `${type}${suffix}`);
      m.zoneKeys[type] = {
        enabled: k('Enabled'),
        min: k('Min'),
        max: k('Max'),
        hinted: k('Hinted'),
      };
      const zone = toPascal(type);
      schemaProps.push(
        {
          key: k('Enabled'),
          group: groupKey,
          kind: 'dpBoolean',
          label: `${zone} zone enabled`,
          optional: true,
        },
        {
          key: k('Min'),
          group: groupKey,
          kind: 'dpNumber',
          label: `${zone} zone from${unit}`,
          optional: true,
        },
        {
          key: k('Max'),
          group: groupKey,
          kind: 'dpNumber',
          label: `${zone} zone to${unit}`,
          optional: true,
        },
        {
          key: k('Hinted'),
          group: groupKey,
          kind: 'dpBoolean',
          label: `${zone} zone hinted`,
          optional: true,
        },
      );
    }
    continue;
  }

  if (m.kind === 'enum') {
    schemaProps.push({
      key: m.name,
      group,
      kind: 'enum',
      label,
      optional: m.default === undefined,
      defaultValue: m.default,
      member: m,
    });
    continue;
  }

  if (m.kind === 'number' && primaryNames.includes(m.name)) {
    schemaProps.push({
      key: m.name,
      group,
      kind: 'dpNumber',
      label,
      optional: false,
      defaultValue: m.default ?? 0,
      member: m,
      primary: true,
    });
    continue;
  }

  const suffix =
    m.kind === 'enumList'
      ? ` (${m.options.join(', ')})`
      : m.kind === 'list'
        ? ` (list of ${m.itemType === 'primitive' ? 'values' : `${m.itemType}s`})`
        : m.kind === 'json'
          ? ' (JSON)'
          : '';
  schemaProps.push({
    key: m.name,
    group,
    kind: DP_KIND[m.kind],
    label: label + suffix + (m.kind === 'json' ? '' : hint),
    optional: true,
    member: m,
  });
}

for (const e of events) {
  for (const t of e.targets) {
    schemaProps.push({
      key: t.key,
      group: 'events',
      kind: 'dpTarget',
      label: `${e.words[0].toUpperCase()}${e.words.slice(1)}: ${t.path.join('.') || 'value'} → write to`,
      optional: true,
    });
  }
}

if (schemaProps.some((p) => p.group === 'setpoint')) groups.set('setpoint', { label: 'Setpoint' });
groups.set('display', { label: 'Display' });
for (const [key, value] of prefixGroups) groups.set(key, value);
// Advice groups were added in member order; move them after the others.
for (const [key, value] of [...groups]) {
  if (key.endsWith('Zones')) {
    groups.delete(key);
    groups.set(key, value);
  }
}
if (events.some((e) => e.targets.length))
  groups.set('events', { label: 'Event values', defaultClosed: true });
groups.set('interaction', { label: 'Interaction', defaultClosed: true });

for (const key of [...groups.keys()]) {
  if (key !== 'interaction' && !schemaProps.some((p) => p.group === key)) groups.delete(key);
}

// ── Code generation ──────────────────────────────────────────────────────

const q = (value) => `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const literal = (value) =>
  typeof value === 'string'
    ? q(value)
    : Array.isArray(value)
      ? `[${value.map(literal).join(', ')}]`
      : String(value);
const dpVar = (key) => `${key}Dp`;
const propKey = (name) => (/^[A-Za-z_$][\w$]*$/.test(name) ? name : q(name));

const componentKeys = members.map((m) => m.name);
const componentImportPath = `@oicl/openbridge-webcomponents/dist/${modulePath}.js`;
const reactImportPath = `@oicl/openbridge-webcomponents-react/${modulePath}.js`;

const classDescription = (declaration.description ?? declaration.summary ?? '')
  .replace(/`<obc-[\w-]+>`\s*[—–-]\s*/, '')
  .split(/\n\s*\n/)[0]
  .replace(/\s+/g, ' ')
  .trim();
const elementDescription =
  classDescription && classDescription.length < 200
    ? `${classDescription.replace(/\.$/, '')} (OpenBridge design system).`
    : `${displayName} (OpenBridge design system).`;

const sizeDoc = {
  square: 'The component is kept square and scaled to the largest size that fits.',
  fill: 'The component fills the available space.',
  intrinsic: 'The component keeps its natural size and is centered in the available space.',
}[shape];

const eventProps = events.map((e) => e.prop);
const propsTypeParts = [
  componentKeys.length && `Partial<Pick<${obcClass}Element, ${componentKeys.map(q).join(' | ')}>>`,
  eventProps.length &&
    `Partial<Pick<ComponentProps<typeof ${obcClass}>, ${eventProps.map(q).join(' | ')}>>`,
  '{ onClick?: () => void }',
].filter(Boolean);

const componentBody =
  shape === 'intrinsic'
    ? `  return (
    <div className={cx(classNames.root, onClick && classNames.clickable)}>
      <${obcClass} onClick={onClick} {...definedProps(props)} />
    </div>
  );`
    : `  return (
    <AutoSizer className={cx(classNames.root, onClick && classNames.clickable)}>
      {({ width, height }) => {
        ${shape === 'square' ? 'const size = Math.min(width, height);\n        ' : ''}return (
          <${obcClass}
            style={{ display: 'block', ${shape === 'square' ? 'width: size, height: size' : 'width, height'} }}
            onClick={onClick}
            {...definedProps(props)}
          />
        );
      }}
    </AutoSizer>
  );`;

const componentSource = `${
  componentKeys.length
    ? `import type { ${obcClass} as ${obcClass}Element } from '${componentImportPath}';\n`
    : ''
}import { ${obcClass} } from '${reactImportPath}';
import { className, cx } from '@hmiproject/helio-sdk';
${eventProps.length ? "import type { ComponentProps } from 'react';\n" : ''}${shape === 'intrinsic' ? '' : "import { AutoSizer } from '../utils/AutoSizer';\n"}import { definedProps } from '../utils/valueMapping';

export type ${propsType} = ${propsTypeParts.join(' & ')};

const classNames = {
  root: className({
${
  shape === 'intrinsic'
    ? `    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
`
    : `    minHeight: ${shape === 'square' ? 120 : 48},
`
}    fontFamily: "'Noto Sans', sans-serif",
  }),
  clickable: className({ cursor: 'pointer' }),
};

/**
 * Presentational wrapper around OpenBridge's \`<${tag}>\`. Receives fully
 * resolved values; all HELIO dynamic property handling happens in the element.
 * ${sizeDoc}
 *
 * ${GENERATED_MARKER}.
 */
export function ${Name}({ onClick, ...props }: ${propsType}) {
${componentBody}
}
`;

// Element

const VALUE_TYPE = {
  dpNumber: 'NumericValue',
  dpBoolean: 'Boolean',
  dpString: 'String',
  dpPrimitive: 'PrimitiveValue',
  dpAny: '*',
  dpTarget: '*',
};
const READER = {
  dpNumber: '{ valueType: values.Number() }',
  dpBoolean: '{ valueType: values.Boolean() }',
  dpString: '{ valueType: values.String() }',
};

function schemaEntry(p) {
  const lines = [`label: ${q(p.label)}`, `propGroup: ${q(p.group)}`];
  if (p.kind === 'enum') {
    lines.push(`options: [${p.member.options.map(q).join(', ')}]`);
    lines.push(`optional: ${p.optional}`);
    if (!p.optional) lines.push(`defaultValue: ${q(p.defaultValue)}`);
    return `${p.key}: props.Enum({\n      ${lines.join(',\n      ')},\n    }),`;
  }
  lines.push(`valueType: ${q(VALUE_TYPE[p.kind])}`);
  lines.push(`optional: ${p.optional}`);
  if (!p.optional) {
    lines.push(`defaultValue: dynamicProperties.StaticValue(${literal(p.defaultValue)})`);
  }
  return `${p.key}: props.DynamicProperty({\n      ${lines.join(',\n      ')},\n    }),`;
}

const dpProps = schemaProps.filter((p) => p.kind !== 'enum');
const usedHelpers = new Set();
const use = (name) => (usedHelpers.add(name), name);

/**
 * Fallbacks that differ from the manifest default, for known OpenBridge quirks.
 */
const FALLBACK_OVERRIDES = {
  // `undefined` makes the component fall back to the deprecated
  // `rotationsPerMinute = 1`, so the ROT dots would spin forever.
  rateOfTurnDegreesPerMinute: () => '0',
  // Without a course the COG arrow should hide under the HDG arrow.
  courseOverGround: () => (primaryNames.includes('heading') ? 'headingRaw ?? 0' : undefined),
};

function withFallback(expr, member) {
  const override = FALLBACK_OVERRIDES[member.name]?.();
  if (override !== undefined) return `${expr} ?? ${override}`;
  return member.default !== undefined && !Array.isArray(member.default)
    ? `${expr} ?? ${literal(member.default)}`
    : expr;
}

const cast = (m) => `${propsType}[${q(m.name)}]`;

function valueExpression(m) {
  const p = `p.${m.name}`;
  const dp = dpVar(m.name);
  switch (m.kind) {
    case 'number':
      if (primaryNames.includes(m.name)) return `${m.name}Raw ?? ${literal(m.default ?? 0)}`;
      return withFallback(`${use('optionalNumber')}(${p}, ${dp})`, m);
    case 'boolean':
      return withFallback(`${use('optionalBoolean')}(${p}, ${dp})`, m);
    case 'string':
      return withFallback(`${use('optionalString')}(${p}, ${dp})`, m);
    case 'primitive':
      return `${use('optionalPrimitive')}(${p}, ${dp}) as ${cast(m)}`;
    case 'list':
      return `${use('optionalList')}(${p}, ${dp}, ${q(m.itemType)}) as ${cast(m)}`;
    case 'json':
      return `${use('optionalJson')}(${p}, ${dp}) as ${cast(m)}`;
    case 'enum':
      if (m.resolved.numeric) {
        const map = m.resolved.values
          .map((v) => `${propKey(v.key)}: ${literal(v.value)}`)
          .join(', ');
        return `(${p} === undefined ? undefined : ({ ${map} } as Record<string, number | string>)[${p}]) as ${cast(m)}`;
      }
      return `${p} as ${cast(m)}`;
    case 'enumList':
      return `(${p} === undefined
            ? undefined
            : ${use('parseEnumList')}(${dp}.value, [${m.options.map(q).join(', ')}])) as ${cast(m)}`;
    case 'priority':
      return `(${use('optionalBoolean')}(p.enhancedPriority, ${dpVar('enhancedPriority')}) ? 'enhanced' : 'regular') as ${propsType}['priority']`;
    case 'state': {
      const available = primaryNames.length
        ? primaryNames.map((n) => `${n}Raw !== undefined`).join(' && ')
        : 'true';
      return `${use('deriveInstrumentState')}({
            isOff: ${use('optionalBoolean')}(p.isOff, ${dpVar('isOff')}),
            isLoading: optionalBoolean(p.isLoading, ${dpVar('isLoading')}),
            valueAvailable: ${available},
          })`;
    }
    case 'advice': {
      const builder = use(m.angle ? 'buildAngleAdvices' : 'buildLinearAdvices');
      use('optionalBoolean');
      use('optionalNumber');
      const zones = ['advice', 'caution'].map((type) => {
        const k = m.zoneKeys[type];
        return `{
              type: AdviceType.${type},
              enabled: optionalBoolean(p.${k.enabled}, ${dpVar(k.enabled)}),
              min: optionalNumber(p.${k.min}, ${dpVar(k.min)}),
              max: optionalNumber(p.${k.max}, ${dpVar(k.max)}),
              hinted: optionalBoolean(p.${k.hinted}, ${dpVar(k.hinted)}),
            }`;
      });
      let expr = `${builder}([${zones.join(', ')}])`;
      const expected = m.angle ? ['minAngle', 'maxAngle'] : ['min', 'max'];
      if (m.minKey !== expected[0] || m.maxKey !== expected[1]) {
        expr += `.map(({ ${expected[0]}, ${expected[1]}, ...rest }) => ({ ...rest, ${m.minKey}: ${expected[0]}, ${m.maxKey}: ${expected[1]} }))`;
      }
      return `${expr} as ${cast(m)}`;
    }
  }
}

const eventAttributes = events.map((e) => {
  const writes = e.targets.map(
    (t) =>
      `              ${use('writeValue')}(p.${t.key}, ${dpVar(t.key)}, event.detail${t.path.map((part) => `?.${part}`).join('')});`,
  );
  return `          ${e.prop}={
            interactive
              ? (${writes.length ? 'event' : ''}) => {
${writes.join('\n')}${writes.length ? '\n' : ''}                  if (${e.actionVar}.canCall === true) ${e.actionVar}.call();
                }
              : undefined
          }`;
});

const componentAttributes = [
  ...members.map((m) => `          ${m.name}={${valueExpression(m)}}`),
  ...eventAttributes,
].join('\n');

const primaryReads = primaryNames
  .map((n) => {
    use('toFiniteNumber');
    return `    const ${n}Raw = ${dpVar(n)}.canRead === false ? undefined : toFiniteNumber(${dpVar(n)}.value);`;
  })
  .join('\n');

const needsValues = dpProps.some((p) => READER[p.kind]);
const sdkImports = [
  'createElement',
  'createPropsSchema',
  dpProps.some((p) => !p.optional) && 'dynamicProperties',
  'props',
  'traits',
  'useAction',
  dpProps.length && 'useDynamicProperty',
  'useRenderMode',
  needsValues && 'values',
].filter(Boolean);
const usesPropsType = componentAttributes.includes(`${propsType}[`);
const actionVars = ['onClick', ...events.map((e) => e.actionVar)];

const elementSource = `import { ${sdkImports.join(', ')} } from '@hmiproject/helio-sdk';
${has('advice') ? "import { AdviceType } from '@oicl/openbridge-webcomponents/dist/navigation-instruments/watch/advice.js';\n" : ''}import { Fragment } from 'react';
import { namespace } from '../namespace';
import { ${Name}${usesPropsType ? `, type ${propsType}` : ''} } from '../components/${Name}';
__HELPERS__
/**
 * OpenBridge ${displayName.toLowerCase()} (\`<${tag}>\`) as a HELIO Control.
 *
 * ${GENERATED_MARKER} from the OpenBridge custom elements manifest.${
   skipped.length
     ? `\n *\n * Not generated (add manually if needed):\n${skipped.map((s) => ` * - \`${s.name}\` (${s.type}) – ${s.reason}`).join('\n')}`
     : ''
 }
 */
export const ${elementVar} = createElement(namespace, {
  name: ${q(`OpenBridge ${displayName}`)},
  description: ${q(elementDescription)},
  category: ${q(categoryInfo.helioCategory)},
  icon: { name: ${q(icon)} },

  traits: [traits.Control],

  propsGroups: {
${[...groups].map(([key, g]) => `    ${key}: { label: ${q(g.label)}${g.defaultClosed ? ', defaultClosed: true' : ''} },`).join('\n')}
  },

  propsSchema: createPropsSchema().initial({
${schemaProps.map((p) => `    ${schemaEntry(p)}`).join('\n')}
    onClick: props.Action({
      label: 'On click',
      propGroup: 'interaction',
      optional: true,
    }),
${events
  .map(
    (e) => `    ${e.prop}: props.Action({
      label: ${q(e.label)},
      propGroup: 'interaction',
      optional: true,
    }),`,
  )
  .join('\n')}
  }),

  Component(p) {
    const renderMode = useRenderMode();
    const interactive = renderMode !== 'PreviewEdit';

${dpProps.map((p) => `    const ${dpVar(p.key)} = useDynamicProperty(p.${p.key}${READER[p.kind] ? `, ${READER[p.kind]}` : ''});`).join('\n')}

    const onClick = useAction(p.onClick);
${events.map((e) => `    const ${e.actionVar} = useAction(p.${e.prop});`).join('\n')}

${
  dpProps.length
    ? `    // Dynamic properties need to be mounted to subscribe to value changes.
    const subscriptions = [${dpProps.map((p) => dpVar(p.key)).join(', ')}];
`
    : ''
}
${primaryReads}

    const clickable = onClick.canCall === true && interactive;

    return (
      <Fragment>
${
  dpProps.length
    ? `        {subscriptions.map((dp, index) => (
          <Fragment key={index}>{dp.render()}</Fragment>
        ))}
`
    : ''
}${actionVars.map((a) => `        {${a}.render()}`).join('\n')}

        <${Name}
${componentAttributes}
          onClick={clickable ? onClick.call : undefined}
        />
      </Fragment>
    );
  },
});
`.replace('__HELPERS__', () =>
  usedHelpers.size
    ? `import { ${[...usedHelpers].sort().join(', ')} } from '../utils/valueMapping';\n`
    : '',
);

// Stories

const storyArgs = [];
if (has('state')) storyArgs.push(`state: 'active' as ${propsType}['state']`);
for (const m of members.filter((x) => x.defaultOverridden)) {
  storyArgs.push(`${m.name}: ${literal(m.default)} as ${cast(m)}`);
}
for (const n of primaryNames) {
  const m = members.find((x) => x.name === n);
  storyArgs.push(`${n}: ${m.default && m.default !== 0 ? literal(m.default) : 42}`);
}

const argTypes = members
  .filter(
    (m) =>
      (m.kind === 'enum' && !m.resolved.numeric) || m.kind === 'state' || m.kind === 'priority',
  )
  .map((m) => {
    const options =
      m.kind === 'state'
        ? ['active', 'loading', 'off']
        : m.kind === 'priority'
          ? ['regular', 'enhanced']
          : m.options;
    return `    ${m.name}: { control: 'select', options: [${options.map(q).join(', ')}] },`;
  })
  .concat(primaryNames.map((n) => `    ${n}: { control: 'number' },`));

const storySize = {
  square: [[420, 420], [640, 240], 'WideContainer'],
  fill: [[640, 160], [320, 96], 'SmallContainer'],
  intrinsic: [[320, 200], [160, 120], 'SmallContainer'],
}[shape];

const storiesSource = `// ${GENERATED_MARKER}.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ${Name}${storyArgs.length ? `, type ${propsType}` : ''} } from './${Name}';

const meta = {
  title: ${q(`${categoryInfo.storyPrefix}/${displayName}`)},
  component: ${Name},
  // The container size comes from \`parameters.size\`, so stories can show how
  // the component behaves in differently sized containers.
  parameters: { size: { width: ${storySize[0][0]}, height: ${storySize[0][1]} } },
  decorators: [
    (Story, { parameters }) => (
      <div style={{ ...parameters.size, outline: '1px dashed #999' }}>
        <Story />
      </div>
    ),
  ],
  argTypes: {
${argTypes.join('\n')}
  },
  args: {
${storyArgs.map((a) => `    ${a},`).join('\n')}
  }${storyArgs.length ? ` satisfies ${propsType}` : ''},
} satisfies Meta<typeof ${Name}>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const ${storySize[2]}: Story = {
  parameters: { size: { width: ${storySize[1][0]}, height: ${storySize[1][1]} } },
};
${
  has('state')
    ? `
export const Loading: Story = {
  args: { state: 'loading' as ${propsType}['state'] },
};
`
    : ''
}`;

// Docs

const KIND_LABEL = {
  dpNumber: 'DP NumericValue',
  dpBoolean: 'DP Boolean',
  dpString: 'DP String',
  dpPrimitive: 'DP PrimitiveValue',
  dpAny: 'DP (any)',
  dpTarget: 'DP (write target)',
  enum: 'Enum',
};

const docsPath = categoryInfo.docsPath(shortTag, area);
const docsLink = docsPath
  ? `<https://openbridge-storybook.web.app/?path=/docs/${docsPath}--docs>`
  : `<https://openbridge-storybook.web.app/> (search for "${shortTag}")`;

const docsSource = `# OpenBridge ${displayName} – HELIO Extension Element

${GENERATED_MARKER} from \`<${tag}>\` (${categoryInfo.label.toLowerCase()}).

- OpenBridge docs: ${docsLink}
- Typings: \`node_modules/@oicl/openbridge-webcomponents/dist/${modulePath}.d.ts\`

## Files

\`\`\`
${srcDir}/components/${Name}.tsx
${srcDir}/elements/${Name}Element.tsx      (export \`${elementVar}\`)
\`\`\`

Sizing: **${shape}** – ${sizeDoc.toLowerCase().replace(/\.$/, '')}.
${
  has('state')
    ? primaryNames.length
      ? `Main value${primaryNames.length > 1 ? 's' : ''}: ${primaryNames.map((n) => `\`${n}\``).join(', ')} – required; the component shows \`loading\` while ${primaryNames.length > 1 ? 'any of them is' : 'it is'} unreadable.`
      : 'The state follows "Instrument off" / "Instrument loading".'
    : primaryNames.length
      ? `Main value${primaryNames.length > 1 ? 's' : ''}: ${primaryNames.map((n) => `\`${n}\``).join(', ')} (required).`
      : ''
}

Unset optional props are **not passed** to the web component, so its own
defaults apply. List props accept an array or a separated string
(\`"1, 2, 3"\`); JSON props accept an object/array or a JSON string.
${
  events.length
    ? `
## Events

Each event runs its HELIO action. Event values are first written to the
configured "write to" dynamic properties (e.g. a writable data variable).

| Event | Action | Written values |
|---|---|---|
${events.map((e) => `| ${e.words} | \`${e.prop}\` | ${e.targets.map((t) => `\`${t.path.join('.') || 'value'}\` → \`${t.key}\``).join(', ') || '–'} |`).join('\n')}
`
    : ''
}
## Properties

| Key | IDE label | Kind | Group | obc prop |
|---|---|---|---|---|
${schemaProps
  .map(
    (p) =>
      `| \`${p.key}\` | ${p.label.replace(/\|/g, '\\|')} | ${KIND_LABEL[p.kind]}${p.optional ? ' opt' : `, default \`${formatDefault(p.defaultValue)}\``} | ${groups.get(p.group)?.label ?? p.group} | ${p.member ? `\`${p.member.name}\`` : p.kind === 'dpTarget' ? 'event value' : p.key.startsWith('is') ? '`state`' : 'advice zone'} |`,
  )
  .join('\n')}
| \`onClick\` | On click | Action opt | Interaction | click |
${events.map((e) => `| \`${e.prop}\` | ${e.label} | Action opt | Interaction | ${e.words} event |`).join('\n')}
${
  skipped.length
    ? `
## Not generated

These \`<${tag}>\` properties cannot come from HELIO values:

${skipped.map((s) => `- \`${s.name}\` (\`${s.type}\`) – ${s.reason}`).join('\n')}
`
    : ''
}`;

// ── Checks on the target project ─────────────────────────────────────────

function readIfExists(path) {
  return existsSync(path) ? readFileSync(path, 'utf8') : undefined;
}

/** Runtime helpers the generated code imports, and the exports it needs from them. */
const neededRuntime = {
  'utils/valueMapping.ts': ['definedProps', ...usedHelpers],
  ...(shape === 'intrinsic' ? {} : { 'utils/AutoSizer.tsx': ['AutoSizer'] }),
  'namespace.ts': ['namespace'],
};

const runtimeWrites = [];
for (const [file, exportsNeeded] of Object.entries(neededRuntime)) {
  const existing = readIfExists(inSrc(file));
  if (existing === undefined) {
    runtimeWrites.push(file);
    if (file === 'utils/valueMapping.ts' && !existsSync(inSrc('dynamicProperties/angleMath.ts'))) {
      runtimeWrites.push('dynamicProperties/angleMath.ts');
    }
    continue;
  }
  const missing = exportsNeeded.filter(
    (name) => !new RegExp(`export (?:function|const|class) ${name}\\b`).test(existing),
  );
  if (missing.length) {
    fail(
      `${srcDir}/${file} exists but lacks: ${missing.join(', ')}.\n` +
        `Update it from the embedded copy: node ${relative(process.cwd(), SCRIPT_PATH)} --print-runtime ${file}`,
    );
  }
}

const storybookInstalled = existsSync(inRoot('node_modules/@storybook/react-vite'));
const writeStories = !args['no-stories'] && storybookInstalled;
const cssImport = "import '@oicl/openbridge-webcomponents/dist/openbridge.css';";

const packageJson = JSON.parse(readFileSync(inRoot('package.json'), 'utf8'));
const deps = { ...packageJson.dependencies, ...packageJson.devDependencies };
const rollupConfig = ['rollup.config.mjs', 'rollup.config.js', 'rollup.config.ts']
  .map((f) => readIfExists(inRoot(f)))
  .find(Boolean);
if (rollupConfig !== undefined) {
  if (!/import-css|postcss|rollup-plugin-styles|rollup-plugin-css/.test(rollupConfig)) {
    warn(
      'rollup has no CSS plugin – the OpenBridge stylesheet will not be bundled. Add:\n' +
        "    npm i -D rollup-plugin-import-css   and in rollup.config: import css from 'rollup-plugin-import-css';\n" +
        '    plugins: [ …, css({ inject: true, minify: true }), nodeResolve(), … ]',
    );
  }
  if (!/process\.env\.NODE_ENV/.test(rollupConfig)) {
    warn(
      "rollup does not replace process.env.NODE_ENV – Lit crashes in the browser. Use @rollup/plugin-replace with { 'process.env.NODE_ENV': JSON.stringify('production') }.",
    );
  }
}
if (!deps['@oicl/openbridge-webcomponents'] || !deps['@oicl/openbridge-webcomponents-react']) {
  warn('OpenBridge packages are installed but not listed in package.json dependencies.');
}
if (!args['no-stories'] && !storybookInstalled) {
  warn('Storybook (@storybook/react-vite) is not installed – no stories were generated.');
}

// ── Write files ──────────────────────────────────────────────────────────

const files = [
  [`${srcDir}/components/${Name}.tsx`, componentSource],
  writeStories && [`${srcDir}/components/${Name}.stories.tsx`, storiesSource],
  [`${srcDir}/elements/${Name}Element.tsx`, elementSource],
  !args['no-docs'] && [`docs/openbridge-${shortTag}.md`, docsSource],
].filter(Boolean);

if (args['dry-run']) {
  for (const [file, source] of files) console.log(`\n── ${file} ──\n${source}`);
  if (runtimeWrites.length)
    console.log(`\nWould create runtime helpers: ${runtimeWrites.join(', ')}`);
  process.exit(0);
}

for (const [file] of files) {
  const existing = readIfExists(inRoot(file));
  if (existing === undefined) continue;
  if (![GENERATED_MARKER, ...LEGACY_MARKERS].some((marker) => existing.includes(marker))) {
    fail(`${file} exists and was not generated by this script – refusing to overwrite it.`);
  }
  if (!args.force) fail(`${file} already exists. Use --force to regenerate it.`);
}

const writeFile = (file, source) => {
  mkdirSync(dirname(inRoot(file)), { recursive: true });
  writeFileSync(inRoot(file), source);
};

for (const [file, source] of files) writeFile(file, source);
for (const file of runtimeWrites) writeFile(`${srcDir}/${file}`, runtimeFiles()[file]);
if (runtimeWrites.includes('namespace.ts')) {
  warn(
    `Created ${srcDir}/namespace.ts with a placeholder – set your reverse-domain namespace before publishing.`,
  );
}

/** Appends `item` to the array literal after `key:`, keeping comments intact. */
function appendToArray(source, key, item) {
  const start = source.search(new RegExp(`${key}\\s*:\\s*\\[`));
  if (start < 0) return undefined;
  const open = source.indexOf('[', start);
  let depth = 0;
  let close = -1;
  for (let i = open; i < source.length; i++) {
    if (source[i] === '[') depth++;
    else if (source[i] === ']' && --depth === 0) {
      close = i;
      break;
    }
  }
  if (close < 0) return undefined;
  const inner = source.slice(open + 1, close);
  const code = inner
    .replace(/\/\/.*$/gm, (c) => ' '.repeat(c.length))
    .replace(/\/\*[\s\S]*?\*\//g, (c) => ' '.repeat(c.length));
  const lastCode = code.trimEnd().length - 1;
  const needsComma = lastCode >= 0 && code[lastCode] !== ',' && code.trim() !== '';
  const before = needsComma
    ? `${inner.slice(0, lastCode + 1)},${inner.slice(lastCode + 1)}`
    : inner;
  return `${source.slice(0, open + 1)}${before.trimEnd()}\n    ${item},\n  ${source.slice(close)}`;
}

const written = files.map(([file]) => file);
if (!args['no-register']) {
  const mainPath = inRoot(mainFile);
  let main = readIfExists(mainPath);
  if (main === undefined) {
    warn(`${mainFile} not found – register ${elementVar} manually.`);
  } else {
    let changed = false;
    if (!main.includes(`/elements/${Name}Element'`)) {
      const updated = appendToArray(main, 'elements', elementVar);
      if (updated === undefined) {
        warn(`No "elements: [...]" found in ${mainFile} – register ${elementVar} manually.`);
      } else {
        const importLine = `import { ${elementVar} } from './elements/${Name}Element';\n`;
        const imports = [...updated.matchAll(/^import .*;\n/gm)];
        const lastImport = imports.pop();
        const insertAt = lastImport ? lastImport.index + lastImport[0].length : 0;
        main = updated.slice(0, insertAt) + importLine + updated.slice(insertAt);
        changed = true;
      }
    }
    if (!main.includes(cssImport)) {
      const firstImportEnd = main.search(/^import .*;\n/m);
      const at = firstImportEnd < 0 ? 0 : main.indexOf('\n', firstImportEnd) + 1;
      main = main.slice(0, at) + cssImport + '\n' + main.slice(at);
      changed = true;
      console.log(`Added the OpenBridge stylesheet import to ${mainFile}.`);
    }
    if (changed) {
      writeFileSync(mainPath, main);
      written.push(mainFile);
    }
  }

  const previewPath = ['.storybook/preview.tsx', '.storybook/preview.ts']
    .map((f) => inRoot(f))
    .find((f) => existsSync(f));
  if (writeStories && previewPath && !readFileSync(previewPath, 'utf8').includes(cssImport)) {
    const preview = readFileSync(previewPath, 'utf8');
    const at = preview.search(/^import .*;\n/m);
    const pos = at < 0 ? 0 : preview.indexOf('\n', at) + 1;
    writeFileSync(previewPath, preview.slice(0, pos) + cssImport + '\n' + preview.slice(pos));
    written.push(relative(root, previewPath));
  }
}

const allWritten = [...written, ...runtimeWrites.map((f) => `${srcDir}/${f}`)];
const prettierBin = inRoot('node_modules/.bin/prettier');
if (existsSync(prettierBin)) {
  execFileSync(prettierBin, ['--write', ...allWritten], { cwd: root, stdio: 'ignore' });
} else {
  warn('prettier is not installed locally – generated files are not formatted.');
}

console.log(
  `\x1b[32mCreated OpenBridge ${displayName} (<${tag}>, ${categoryInfo.label.toLowerCase()})\x1b[0m`,
);
for (const file of allWritten) console.log(`  ${file}`);
console.log(
  `  shape: ${shape}, main value: ${primaryNames.join(', ') || '–'}, icon: ${icon}` +
    (events.length ? `, events: ${events.map((e) => e.words).join(', ')}` : ''),
);
if (skipped.length) {
  console.log('\nNot generated (cannot come from HELIO values):');
  for (const s of skipped) console.log(`  - ${s.name}: ${s.type}`);
}
for (const message of warnings) console.log(`\n\x1b[33mWarning:\x1b[0m ${message}`);

// ── Embedded runtime helpers ─────────────────────────────────────────────
// Written into a target project when missing. The synced ones are copies of
// this repo's files – refresh them with --sync-runtime after changing those.

function runtimeFiles() {
  return {
    ...syncedRuntimeFiles(),
    'namespace.ts': `import { createNamespace } from '@hmiproject/helio-sdk';

export const namespace = createNamespace({
  // Change this so it matches your company's domain name in
  // https://en.wikipedia.org/wiki/Reverse_domain_name_notation
  name: 'com.my-company.my-extension',
});
`,
  };
}

// @runtime-files-start
// prettier-ignore
function syncedRuntimeFiles() {
  return {
    "utils/AutoSizer.tsx": "import { className, cx } from '@hmiproject/helio-sdk';\nimport { useEffect, useRef, useState, type ReactNode } from 'react';\n\nexport type Size = { width: number; height: number };\n\ntype AutoSizerProps = {\n  className?: string;\n  children: (size: Size) => ReactNode;\n};\n\nconst classNames = {\n  root: className({\n    width: '100%',\n    height: '100%',\n    display: 'flex',\n    alignItems: 'center',\n    justifyContent: 'center',\n    overflow: 'hidden',\n  }),\n};\n\n/**\n * Fills its parent, measures the available space and renders its children\n * with that size. Children are centered and only rendered once the size is\n * known (both dimensions > 0).\n */\nexport function AutoSizer({ className, children }: AutoSizerProps) {\n  const ref = useRef<HTMLDivElement>(null);\n  const [size, setSize] = useState<Size>({ width: 0, height: 0 });\n\n  useEffect(() => {\n    const element = ref.current;\n    if (!element) return;\n\n    const observer = new ResizeObserver(([entry]) => {\n      const { width, height } = entry.contentRect;\n      setSize((previous) =>\n        previous.width === width && previous.height === height ? previous : { width, height },\n      );\n    });\n    observer.observe(element);\n    return () => observer.disconnect();\n  }, []);\n\n  return (\n    <div ref={ref} className={cx(classNames.root, className)}>\n      {size.width > 0 && size.height > 0 && children(size)}\n    </div>\n  );\n}\n",
    "utils/valueMapping.ts": "import type { LinearAdvice } from '@oicl/openbridge-webcomponents/dist/navigation-instruments/thruster/advice.js';\nimport { InstrumentState } from '@oicl/openbridge-webcomponents/dist/navigation-instruments/types.js';\nimport type {\n  AdviceType,\n  AngleAdvice,\n} from '@oicl/openbridge-webcomponents/dist/navigation-instruments/watch/advice.js';\nimport { normalizeAngle } from '../dynamicProperties/angleMath';\n\n// Helpers shared by all instrument elements that translate loosely typed HELIO\n// values (dynamic properties can deliver anything a PLC/OPC UA variable\n// produces) into the strongly typed inputs of the OpenBridge components.\n\n/** Returns a finite number, or `undefined` for anything else (incl. numeric strings that are empty). */\nexport function toFiniteNumber(value: unknown): number | undefined {\n  if (typeof value === 'number') return Number.isFinite(value) ? value : undefined;\n  if (typeof value === 'string' && value.trim() !== '') {\n    const parsed = Number(value);\n    return Number.isFinite(parsed) ? parsed : undefined;\n  }\n  return undefined;\n}\n\n/** Interprets booleans, numbers (0 = false) and strings like \"true\"/\"on\"/\"1\". */\nexport function toBoolean(value: unknown): boolean | undefined {\n  if (typeof value === 'boolean') return value;\n  if (typeof value === 'number') return Number.isFinite(value) ? value !== 0 : undefined;\n  if (typeof value === 'string') {\n    const normalized = value.trim().toLowerCase();\n    if (['true', '1', 'on', 'yes'].includes(normalized)) return true;\n    if (['false', '0', 'off', 'no'].includes(normalized)) return false;\n  }\n  return undefined;\n}\n\n/** Lowercases and strips spaces, `_` and `-`, for lenient string matching. */\nexport function normalizeKey(value: string): string {\n  return value.replace(/[\\s_-]/g, '').toLowerCase();\n}\n\ntype ReadableValue = { value: unknown; canRead: boolean | undefined };\n\n/**\n * Reads an optional dynamic property as number. Props that are not configured\n * (`ref === undefined`) or not readable must not contribute values.\n */\nexport function optionalNumber(ref: unknown, dp: ReadableValue): number | undefined {\n  return ref === undefined || dp.canRead === false ? undefined : toFiniteNumber(dp.value);\n}\n\n/** Boolean counterpart of {@link optionalNumber}. */\nexport function optionalBoolean(ref: unknown, dp: ReadableValue): boolean | undefined {\n  return ref === undefined || dp.canRead === false ? undefined : toBoolean(dp.value);\n}\n\nexport type InstrumentStateInput = {\n  /** Explicit \"instrument off\" signal, e.g. sensor powered down. */\n  isOff: boolean | undefined;\n  /** Explicit \"loading\" signal. */\n  isLoading: boolean | undefined;\n  /** Whether the instrument's main value is currently readable/available. */\n  valueAvailable: boolean;\n};\n\n/**\n * Derives the instrument state. Explicit signals win; otherwise the instrument\n * shows `loading` while its main value has no value yet (e.g. connection pending).\n */\nexport function deriveInstrumentState(input: InstrumentStateInput): InstrumentState {\n  if (input.isOff) return InstrumentState.off;\n  if (input.isLoading) return InstrumentState.loading;\n  if (!input.valueAvailable) return InstrumentState.loading;\n  return InstrumentState.active;\n}\n\nexport type AdviceZoneInput = {\n  type: AdviceType;\n  enabled: boolean | undefined;\n  min: number | undefined;\n  max: number | undefined;\n  hinted: boolean | undefined;\n};\n\nfunction isCompleteZone(\n  zone: AdviceZoneInput,\n): zone is AdviceZoneInput & { min: number; max: number } {\n  return zone.enabled !== false && zone.min !== undefined && zone.max !== undefined;\n}\n\n/** Builds angle advice arcs; incomplete or disabled zones are skipped. */\nexport function buildAngleAdvices(zones: AdviceZoneInput[]): AngleAdvice[] {\n  return zones.filter(isCompleteZone).map((zone) => ({\n    type: zone.type,\n    minAngle: normalizeAngle(zone.min),\n    maxAngle: normalizeAngle(zone.max),\n    hinted: zone.hinted ?? false,\n  }));\n}\n\n/** Builds linear (e.g. thrust) advice ranges; incomplete or disabled zones are skipped. */\nexport function buildLinearAdvices(zones: AdviceZoneInput[]): LinearAdvice[] {\n  return zones.filter(isCompleteZone).map((zone) => ({\n    type: zone.type,\n    min: Math.min(zone.min, zone.max),\n    max: Math.max(zone.min, zone.max),\n    hinted: zone.hinted ?? false,\n  }));\n}\n\n/** String counterpart of {@link optionalNumber}; numbers are converted to strings. */\nexport function optionalString(ref: unknown, dp: ReadableValue): string | undefined {\n  if (ref === undefined || dp.canRead === false) return undefined;\n  if (typeof dp.value === 'string') return dp.value;\n  if (typeof dp.value === 'number' && Number.isFinite(dp.value)) return String(dp.value);\n  return undefined;\n}\n\n/**\n * Parses a comma/space separated list like `\"hdg, cog\"` into the allowed\n * values (case-insensitive, deduplicated, unknown entries dropped).\n */\nexport function parseEnumList<T extends string>(value: unknown, allowed: readonly T[]): T[] {\n  if (typeof value !== 'string') return [];\n  const parts = value\n    .split(/[\\s,;|]+/)\n    .map((part) => allowed.find((option) => option.toLowerCase() === part.trim().toLowerCase()))\n    .filter((part): part is T => part !== undefined);\n  return [...new Set(parts)];\n}\n\n/**\n * Drops `undefined` entries. The OpenBridge React wrappers assign every passed\n * prop to the element, so passing `undefined` would override the component's\n * own default – leaving the prop out keeps it.\n */\nexport function definedProps<T extends object>(props: T): Partial<T> {\n  return Object.fromEntries(\n    Object.entries(props).filter(([, value]) => value !== undefined),\n  ) as Partial<T>;\n}\n\n/** Reads an optional dynamic property as string, number or boolean, unchanged. */\nexport function optionalPrimitive(\n  ref: unknown,\n  dp: ReadableValue,\n): string | number | boolean | undefined {\n  if (ref === undefined || dp.canRead === false) return undefined;\n  const { value } = dp;\n  if (typeof value === 'number') return Number.isFinite(value) ? value : undefined;\n  return typeof value === 'string' || typeof value === 'boolean' ? value : undefined;\n}\n\nexport type ListItemType = 'number' | 'string' | 'boolean' | 'primitive';\n\nfunction toListItem(value: unknown, type: ListItemType): string | number | boolean | undefined {\n  if (type === 'number') return toFiniteNumber(value);\n  if (type === 'boolean') return toBoolean(value);\n  if (type === 'string') return value === undefined || value === null ? undefined : String(value);\n  return typeof value === 'string' || typeof value === 'boolean' || typeof value === 'number'\n    ? value\n    : undefined;\n}\n\n/**\n * Reads an optional dynamic property as list. Accepts an array value or a\n * separated string (`\"1, 2; 3\"`; number/boolean lists also split on spaces).\n * Entries that cannot be converted are dropped.\n */\nexport function optionalList(\n  ref: unknown,\n  dp: ReadableValue,\n  type: ListItemType,\n): Array<string | number | boolean> | undefined {\n  if (ref === undefined || dp.canRead === false) return undefined;\n  const { value } = dp;\n  const parts = Array.isArray(value)\n    ? value\n    : typeof value === 'string'\n      ? value\n          .split(type === 'number' || type === 'boolean' ? /[\\s,;|]+/ : /[,;|]/)\n          .map((part) => part.trim())\n          .filter((part) => part !== '')\n      : undefined;\n  return parts\n    ?.map((part) => toListItem(part, type))\n    .filter((part): part is string | number | boolean => part !== undefined);\n}\n\n/**\n * Reads an optional dynamic property holding structured data: non-string\n * values (objects, arrays, booleans, numbers) are used as they are, strings are\n * parsed as JSON. Invalid JSON is ignored.\n */\nexport function optionalJson(ref: unknown, dp: ReadableValue): unknown {\n  if (ref === undefined || dp.canRead === false) return undefined;\n  const { value } = dp;\n  if (typeof value !== 'string') return value ?? undefined;\n  if (value.trim() === '') return undefined;\n  try {\n    return JSON.parse(value);\n  } catch {\n    return undefined;\n  }\n}\n\ntype WritableValue = { canWrite: boolean | undefined; setValue?(nextValue: unknown): void };\n\n/**\n * Writes a value to an optional dynamic property (e.g. an event payload into a\n * data variable). Does nothing if the prop is not configured, not writable or\n * the value is missing.\n */\nexport function writeValue(ref: unknown, dp: WritableValue, value: unknown): void {\n  if (ref === undefined || value === undefined || dp.canWrite === false) return;\n  dp.setValue?.(value);\n}\n",
    "dynamicProperties/angleMath.ts": "/** Wraps any angle into the range [0, 360). */\nexport function normalizeAngle(degrees: number): number {\n  return ((degrees % 360) + 360) % 360;\n}\n\nexport type AngleUnit = 'degrees' | 'radians' | 'mils' | 'gradians';\n\n/** Degrees per one unit of the given angle unit (NATO mils: 6400 per turn). */\nconst DEGREES_PER_UNIT: Record<AngleUnit, number> = {\n  degrees: 1,\n  radians: 180 / Math.PI,\n  mils: 360 / 6400,\n  gradians: 360 / 400,\n};\n\nexport type AngleConversionOptions = {\n  unit: AngleUnit;\n  offsetDegrees: number;\n  normalize: boolean;\n};\n\nexport function convertAngle(value: number, options: AngleConversionOptions): number {\n  const degrees = value * DEGREES_PER_UNIT[options.unit] + options.offsetDegrees;\n  return options.normalize ? normalizeAngle(degrees) : degrees;\n}\n\nexport function invertAngleConversion(degrees: number, options: AngleConversionOptions): number {\n  return (degrees - options.offsetDegrees) / DEGREES_PER_UNIT[options.unit];\n}\n\nconst CARDINAL_16 = [\n  'N',\n  'NNE',\n  'NE',\n  'ENE',\n  'E',\n  'ESE',\n  'SE',\n  'SSE',\n  'S',\n  'SSW',\n  'SW',\n  'WSW',\n  'W',\n  'WNW',\n  'NW',\n  'NNW',\n] as const;\n\n/** Converts an angle to a 4-, 8- or 16-point compass rose name. */\nexport function toCardinalDirection(degrees: number, points: 4 | 8 | 16 = 16): string {\n  const step = 16 / points;\n  const index = Math.round(normalizeAngle(degrees) / (360 / points)) % points;\n  return CARDINAL_16[index * step];\n}\n",
  };
}
// @runtime-files-end
